### ISSUE TITLE
Show preview of note content in note list

### ISSUE THREAD

**Issue by mobitar** [standardnotes/web#1]
2 lines max

**Comment by levlaz** [comment]
This is actually surprisingly complex. 

1. Simple way would be to just a single line with an ellipses as you do with the title 
2. Harder way (and requires a choice) would be to use one of the methods outlined here: https://css-tricks.com/line-clampin/

**Comment by mobitar** [comment]
What about this (line clamp): http://stackoverflow.com/a/13924997/458960

**Comment by mobitar** [comment]
But if it's too complicated then a single line will do too.

**Comment by levlaz** [comment]
@mobitar Yeah I saw that, I guess the ellipses don't matter (per that comment it would only show up in webkit). Ill give it a shot!
