### ISSUE TITLE
Revision diffs

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/web#102]
Hi StandardNotes,

Feature request:

It would be great if there was an ability to see diffs between the selected and the previous revision

I envisage the notes history menu for a selected revision would be something like

* Preview
* Restore
* Diff

When diff is selected it'll show the preview but with unified diff style format of lines added and removed

Not sure if this is possible or even makes sense with how history is stored - just thought it would be a nice addtion

Cheers

Justin

**Comment by mobitar** [comment]
😵 — that would be extremely complex. I think it would be possible, but would definitely take a huge investment.

**Comment by justinkelly** [comment]
thanks for the update - had assumed it might be to complex
