### ISSUE TITLE
External editors aren't receiving note updates from sync

### ISSUE THREAD

**Issue by kvj** [standardnotes/web#105]
Unlike to built-in editors, external editors are not updated when new note content comes from other side via sync. 

Based on my understanding of `editor.js` code, built-in textarea is getting updated with Angular two-way binding, but not a `setNote()` call. 

So I suggest we need to $watch for `ctrl.note.text` and call `postNoteToExternalEditor()`

**Comment by mobitar** [comment]
Good catch, failed to consider this.

**Comment by mobitar** [comment]
Fixed
