### ISSUE TITLE
Bug: Duplicate Note

### ISSUE THREAD

**Issue by bearMountain** [standardnotes/web#11]
<img width="451" alt="screen shot 2017-01-03 at 12 24 31 am" src="https://cloud.githubusercontent.com/assets/1703113/21600482/0a9709be-d14b-11e6-80b3-7bf4c02e99af.png">
<img width="475" alt="screen shot 2017-01-03 at 12 24 27 am" src="https://cloud.githubusercontent.com/assets/1703113/21600481/0a94526e-d14b-11e6-9a2c-8929ff44c083.png">

Issue:
- Note is duplicated with slight variation

Steps to reproduce:
- I just started in on the second paragraph of my first note and all of the sudden there were two listings for the same note in the middle column
- You can see that the note content is slightly different

Desired outcome:
- there should only be one copy of each note

**Comment by bearMountain** [comment]
<img width="479" alt="screen shot 2017-01-03 at 12 27 55 am" src="https://cloud.githubusercontent.com/assets/1703113/21600512/8555488c-d14b-11e6-8134-9b516611c871.png">
<img width="451" alt="screen shot 2017-01-03 at 12 24 31 am" src="https://cloud.githubusercontent.com/assets/1703113/21600514/8557ef10-d14b-11e6-92fc-2ad69da49483.png">
<img width="475" alt="screen shot 2017-01-03 at 12 24 27 am" src="https://cloud.githubusercontent.com/assets/1703113/21600513/855794b6-d14b-11e6-9a07-a9a19b823bfe.png">


Now there are 3

Steps to reproduce:
- after filing the bug above, I went back and deleted one of the duplicates
- then I began typing on the second paragraph again
- suddenly, there were two new copies in the central column

Desired outcome:
- there should only be one copy of each note

**Comment by mobitar** [comment]
Hmm this is related to this that I just pushed: https://github.com/standardnotes/web/issues/9#issuecomment-270049145

It's treating those as conflicts. I think I have a fix, will push out momentarily.

**Comment by bearMountain** [comment]
<img width="318" alt="screen shot 2017-01-03 at 12 37 15 am" src="https://cloud.githubusercontent.com/assets/1703113/21600605/0aa013ae-d14d-11e6-837c-17cc9a73e6b2.png">

Unstoppable!

**Comment by mobitar** [comment]
Yikes.

**Comment by mobitar** [comment]
Ok should be fixed. Sorry about that.

**Comment by bearMountain** [comment]
How does this play out with the mac client?  Do I need to redownload, or will it get the new code dynamically?

**Comment by mobitar** [comment]
No this one was a server side fix

**Comment by dan-rally** [comment]
Unfortunately I am seeing the same issue, it also results in the cursor jumping around quickly, assuming this is due to the text being moved into duplicated notes. I attach screenshot but due to it being real-world notes I have had to blur most of it, however should be able to see 4 duplicates there. If there is any other information I can supply to help with debugging etc please let me know. Thanks.

![screen_shot_2017-02-21_at_09_15_39](https://cloud.githubusercontent.com/assets/23233956/23158474/3b54560e-f817-11e6-8e59-30f5f1bf72f0.png)

**Comment by mobitar** [comment]
Hey @dan-rally, sorry about that. I was able to replicate the issue and push out a fix. Should be all set now!
