### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by craig-s** [standardnotes/web#112]
I used the Android app to register my email address and enter some notes. Then I tried to use the Web app to access these notes, but I was unable to Log In. I have a pound sign (£) in my password, and think that it is this that is causing the problem.
I've logged out of my Android app, and then back in, successfully - so it's not that I don't know what my password is.
I also registered a second email address using no special characters in the password. With this, I was able to access the related notes from both the Android app and the Web app.

**Comment by mobitar** [comment]
Fixed
