### ISSUE TITLE
Make it easier to collapse panels

### ISSUE THREAD

**Issue by 0xCMP** [standardnotes/web#114]
Should be possible to hide the tags view and also hide the list of notes.

Currently, that's hidden in the menu of the note, but it should be somewhere above.

**Comment by anavarre** [comment]
Yes, having like a drawer icon or something would be only one click VS two clicks now on the menu and then the menu link.

But what would really be best IMO is to have a keyboard shortcut to show/hide.

**Comment by 1vasari** [comment]
@anavarre 

+1 for a keyboard shortcut, that would be neato.

**Comment by harobed** [comment]
> Currently, that's hidden in the menu of the note, but it should be somewhere above.

@0xCMP Where in the menu? I didn't see it in version 2.3.3

**Comment by mobitar** [comment]
Collapsable panels are now a default part of the application. Just hover over the right side of the tags or notes panel and you can resize or collapse. The menu option was removed some time ago.

**Comment by harobed** [comment]
> Just hover over the right side of the tags or notes panel and you can resize or collapse.

Need I drag to collapse it?

If yes, it is possible to add button to collapse and restore panel to initial position (like in this screenshot)? 
<img width="102" alt="capture d ecran 2018-08-15 a 09 46 26" src="https://user-images.githubusercontent.com/230143/44137295-312a2d7c-a070-11e8-94c5-87d0f79d54b6.png">

**Comment by mobitar** [comment]
I'm hoping to make the bars clickable in a future update, so that they toggle between collapsed and expanded.

**Comment by mobitar** [comment]
Available in v3.
