### ISSUE TITLE
Provide instructions on how to run on a private server

### ISSUE THREAD

**Issue by sesceu** [standardnotes/web#116]
Hi,
I'd like to run the standardnotes web editor and extensions on my own server, but I cannot find enough information on how to do it.

I managed to build a docker [container](https://hub.docker.com/r/sesceu/standardfile/) for standardfile (since I'm running all my services using [rancher](http://rancher.com/) and I'm able to use the android app as well as the [original web editor](https://app.standardnotes.org/). This was possible, because there is documentation on standardfile and even some Dockerfiles.

Nothing like this exists for the web client nor for the extensions-server. Can some please update the README.md files for both projects, write a wiki page or point me to some documentation? If I succeed, this might also solve #28, which would be great for developers to improve the web client.

**Comment by mobitar** [comment]
The important part is just configuring your server with the same [instructions for the Standard File server.](https://github.com/standardfile/ruby-server/wiki/Deploying-a-private-Standard-File-server-with-Amazon-EC2-and-Nginx)

The only difference is you would need to install node, npm, and grunt:

```
sudo yum install nodejs npm --enablerepo=epel
npm install grunt
```
