### ISSUE TITLE
Dropdown menu not correctly collapsing

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#123]
The expected behavior when you have a dropdown menu open, is to have it collapse automatically when it loses focus (e.g. when you click somewhere else). However, it's not happening with the web app.

![menu_not_collapsing](https://user-images.githubusercontent.com/293478/27533065-90da6c1e-5a62-11e7-84aa-b3bdaa280adb.gif)

As shown in the above GIF it only works when clicking on the menu bar with the grey background

**Comment by mobitar** [comment]
Thanks, it's a little tricky with external editors (the plain editor should do this). But it's something that can be fixed. Will tackle this at some point.

**Comment by anavarre** [comment]
> it's a little tricky with external editors

So yes, I didn't anticipate this would work with the plain editor and not with the advanced markdown extension. This makes me realize `standardnotes/web` is a catch-all for all issues. Is there a better place to file issues related to a specific extension?

**Comment by mobitar** [comment]
Should be fixed in recent releases.
