### ISSUE TITLE
Search only allowing to match a fixed string, not all words

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#125]
If you're searching for notes with the terms `cache` and `backend` but search for the `cache backend` string instead, then your search will return empty. Instead, we should do a `cache+backend` (not necessarily by specifically adding the plus sign) so that it's certain the search returns something even if the exact string `cache backend` doesn't exist in any of those notes we're looking for. No different from Google Search in a way.

**Comment by mobitar** [comment]
Thanks, this is something I want to adjust soon.

**Comment by mobitar** [comment]
This has been fixed.
