### ISSUE TITLE
There's no way to link to other notes

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#126]
Take this use case:

- You have a standalone note explaining how to use Standard Notes
- You'd like to link to that note within another note, which is about how to use various note-taking applications
- Rather than having to duplicate efforts and write the same how-to again, you'd expect to be able to reference any arbitrary note within a different note

IIRC Evernote does it from its Mac app.

**Comment by ClarkeCC** [comment]
+1

**Comment by brian-hay** [comment]
+1

**Comment by mobitar** [comment]
Many issues covering this already.
