### ISSUE TITLE
Selecting multiple / sorting tags

### ISSUE THREAD

**Issue by ClarkeCC** [standardnotes/web#127]
For example:

I have notes about Ben, Mary, Sam, and Tim. In the tags section for Ben I put #Client # Ben, same would go for the other clients.

I want to be able to select the #Client tag and then have it list down the other tags (#Ben, Mary, etc). Maybe have a box next to each tag and you can tick which tags you want to filter through. 

In the mobile app, at least iOS. You can select the tags, but for example if I choose the #Clients and #Ben. It won't filter down notes with those tags. It would filter all the notes with #Clients. I don't know if it's a bug or if that just the way it works.

Hope this made sense, a little difficult to explain.

**Comment by mobitar** [comment]
So you're just saying allowing selecting multiple tags and listing the combined results of those tags in the notes list?

**Comment by ClarkeCC** [comment]
@mobitar well you certainly explained it that better than I did.

**Comment by mobitar** [comment]
You can select multiple tags with the Folders extension.
