### ISSUE TITLE
Have a folders / tags panel

### ISSUE THREAD

**Issue by ClarkeCC** [standardnotes/web#128]
With the folder extension maybe have a tags tab. There you could select which tags you want to filter through (would apply to #127).

**Comment by mobitar** [comment]
Do you mean multiple selection? Could you post it here: https://github.com/sn-extensions/folders-component

**Comment by ClarkeCC** [comment]
@mobitar Yes and posted.

**Comment by mobitar** [comment]
Multiple selection is now available with Folders extension.
