### ISSUE TITLE
Eliminate the note title

### ISSUE THREAD

**Issue by ClarkeCC** [standardnotes/web#130]
Instead of having a title selection. Have the first line of the note itself be the title. Much more convenient.

**Comment by kslstn** [comment]
I like the idea and wanted to expand on it, but realized that it is unnecessary. When creating a new note, the title field gets keyboard focus. The user can then type something (the title, or just whatever the content of their note should be). Going to the next line (that is the note's body text) is allowed with the Return key. You can also press Tab to go to the tags field and Tab again to go to the body text. ClarkeCC's idea does not speed up writing notes, it would only make the title look like part of the body text, basically eliminating title styling. Title styling may be desirable for some users.

**Comment by mobitar** [comment]
Right, it's sort of a "trendy" thing, and SN tries to stay away from what's trendy and instead do what's sort of the standard. Title field and body field can confuse almost no one, while an all-in-one might throw some people off who have not been exposed to this method of writing notes.

**Comment by mobitar** [comment]
See here also for more discussion: https://github.com/standardnotes/forum/issues/40
