### ISSUE TITLE
Create tags with a # 

### ISSUE THREAD

**Issue by ClarkeCC** [standardnotes/web#131]
Create a tag with a simple # in the note itself would be pretty nice.

**Comment by issmirnov** [comment]
I feel this would detract from the simplicity of the app. I sometimes use hashtags in notes but don't want them to be tags. You'd have to add a toggle somewhere that would be an account level preference or a per note toggle that changes this behavior.

Can this be done with a plugin instead?

**Comment by mobitar** [comment]
Right, this could be done with an editor extension. Not something we have planned but wouldn't be too difficult to develop.

**Comment by Somnambulated** [comment]
I would 1000% +1 this feature
