### ISSUE TITLE
Ability to connect into IFTTT

### ISSUE THREAD

**Issue by cubicgarden** [standardnotes/web#133]
This is a enhancement

Be great to have the ability to connect into IFTTT and other related services.
This can be done by including,
* Adding the ability to send a email to Standard Notes and for that be turned into a note of somekind
* A unique RSS feed of each folder/tag/etc (what ever makes sense)

Theres would be useful but also allow Standard Notes to fit deeper into the wider ecosystem.

Evernote's email feature - https://blog.evernote.com/blog/2015/01/06/email-content-evernote/
Evernote removed RSS a while ago, as it was messing with their bottomline it seems - https://discussion.evernote.com/topic/37000-removing-rss-feed-support-from-public-notebooks/

**Comment by mobitar** [comment]
Sorry, must have missed this. Would be difficult for external services to link into SN due to encryption. But an interesting thought.

**Comment by bouman21** [comment]
Day One also offers end to end encryption and has IFTTT integration, so it's doable.

**Comment by szabado** [comment]
@bouman21 It actually doesn't offer them both at the same time: 
> IFTTT does not currently work with journals that have end-to-end encryption enabled. 
[Source](https://help.dayoneapp.com/tips-and-tutorials/using-ifttt-with-day-one)

**Comment by bouman21** [comment]
Ah yes bugger ... I have(had) one journal that is not using E2E for integration ... sorry!
