### ISSUE TITLE
Switching notes with preview enabled makes display artifact

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#134]
Note: this bug is only happening when using the Advanced Markdown extension.

![display_artifact](https://user-images.githubusercontent.com/293478/27853465-f9698baa-6162-11e7-84e9-e43548faa6eb.gif)

**Comment by mobitar** [comment]
Good catch, thanks. Will investigate this.

**Comment by mobitar** [comment]
Should be fixed in recent releases.
