### ISSUE TITLE
Feature request: more popular Markdown editor

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#138]
Two choices come to mind:

* https://github.com/StackExchange/pagedown because its popularity is de facto huge with all StackExchange sites
* https://github.com/markdown-it/markdown-it because it supports the CommonMark spec

**Comment by mobitar** [comment]
I believe the Simple Markdown Editor uses Markdown It. What advantage would these have over the existing editors in any case?

**Comment by anavarre** [comment]
What I said above: either compatibility with an [upcoming Markdown standard](http://commonmark.org/) or a widely popular markdown editor ([StackExchange's](https://github.com/StackExchange/pagedown)). FYI the [GH flavored Markdown supports CommonMark already](https://github.github.com/gfm/#what-is-github-flavored-markdown-).

IIRC you can determine if the simple/advanced editors respect the spec by following this: https://github.com/jgm/CommonMark#running-tests-against-the-spec

Also, another advantage that I see is that by using a spec or using a very popular markdown editor it's easier to support #137 - I'm a big fan of troubleshooting flowcharts and I know https://github.com/knsv/mermaid has 13k stars on GH which means it's not me only.

IDK who exactly is using Standard Notes but I'm under the impression most will be rather tech savvy. One rather common attribute to tech people is to like writing Markdown because it's exportable, re-usable, common everywhere (and the default for GH, too). Having a great markdown editor and making sure it's a breeze to work with (like supporting flowcharts, mathjax, etc.) with will increase adoption I think.

> I believe the Simple Markdown Editor uses Markdown It.

Are you sure about that? Because copying/pasting the examples from https://markdown-it.github.io/ into a Simple Markdown Editor's note doesn't render e.g. emojis, which is something markdown-it supports OOTB.

**Comment by ianwalter** [comment]
Yea it's unfortunate that both Markdown editors don't support GitHub flavoured Markdown.

**Comment by mobitar** [comment]
We have a few more options now..
