### ISSUE TITLE
Optimize whitespace with tags section 

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#139]
Adding / viewing tags currently works like this:

![apache-tag](https://user-images.githubusercontent.com/293478/28012864-74a84f2e-6567-11e7-83fb-64034779298b.png)

This results in a lot of whitespace being used as a result, especially with the fullscreen view:

![apache-tag-fullscreen](https://user-images.githubusercontent.com/293478/28012863-74a719c4-6567-11e7-9031-b13cf36b0202.png)

I thus suggest optimizing the whitespace usage to adding / viewing tags on the same line. This will also improve the UX a bit.

![whitespace-optimized](https://user-images.githubusercontent.com/293478/28012862-749fa0cc-6567-11e7-82f6-2f3fb8ae3bbb.png)

**Comment by mobitar** [comment]
Hmm interesting. Will consider this. Can you post this here instead https://github.com/sn-extensions/autocomplete-tags

**Comment by anavarre** [comment]
Happy to. I didn't know it existed since it doesn't live under the global https://github.com/standardnotes org.

**Comment by mobitar** [comment]
Good point. I've created and pinned a placeholder repo under /standardnotes so it's more findable: 

<img width="343" alt="screen shot 2017-07-10 at 10 59 11 am" src="https://user-images.githubusercontent.com/3277844/28027506-e34c812e-655e-11e7-8d5d-25e28a626815.png">
