### ISSUE TITLE
Simple Markdown should have the editing and preview panes in synch when scrolling

### ISSUE THREAD

**Issue by anavarre** [standardnotes/web#140]
FYI this is what Ghost CMS is doing. Very, very helpful.

![editing-preview-sync](https://user-images.githubusercontent.com/293478/28056759-5835d0fc-661e-11e7-87b1-e4491e3631dc.gif)

**Comment by mobitar** [comment]
That would be nice..do you know of any open source editors that offer this?

**Comment by anavarre** [comment]
I guess https://markdown-it.github.io/ does it, since it's in the demo?

**Comment by BobTB** [comment]
Can this editor be used somehow, is this supposed work?

**Comment by mobitar** [comment]
The editors we make available are here: https://standardnotes.org/extensions. Although anyone is free to make their own.

**Comment by BobTB** [comment]
Is this "https://forum.standardnotes.org/d/9-how-to-build-an-editor-extension-for-standard-notes" still available somewhere?

**Comment by mobitar** [comment]
The LaTex and Adv MD editor offer this. Still not possible with Simple MD but there's a bounty here: https://github.com/standardnotes/bounties/issues/22
