### ISSUE TITLE
Jankiness in sync after upgrading to extended verification

### ISSUE THREAD

**Issue by issmirnov** [standardnotes/web#142]
I've noticed that my note sync is behaving very strangely after I went through the [verification](https://standardnotes.org/verification) upgrade step. I'm logged in on ~3 OSX devices and ~5 android devices, and I'm seeing very odd behavior:

- tag creation on OSX native client appears to have no effect
- notes added on android device do not appear in web client
- web client on OSX shows empty tags and notes, while android has them

Overall the experience rapidly deteriorated. 

What I've tried
- clearing data and signing in and out on all devices
- importing/exporting notes backups

This started with v1.1/1.2, after the upgrade to verification. Any thoughts?

**Comment by mobitar** [comment]
As part of the verification upgrade, you need to sign out on all open
clients, and upgrade them. So you should be running Android app
version 1.4. Anything lower will result in issues.

**Comment by issmirnov** [comment]
Thanks, after upgrading all accounts and flushing data a few times it sorted itself out!
