### ISSUE TITLE
Make it possible to store the web app offline for later offline use

### ISSUE THREAD

**Issue by thomkeh** [standardnotes/web#144]
The web app can already store your notes offline and then upload them when it is online again. But this requires one to be online to initially load the app. In contrast to that, there are these new "Progressive Web Apps" like this one: https://notella.now.sh/ where my browser offers me to store the actual app offline on my first visit to the website. After that I can use the app completely offline because everything is stored in the browser.

Is this feature something you are considering?

**Comment by mobitar** [comment]
Not something I'm planning, but you can probably do something similar by pressing Cmd/Ctrl + S on the web app to save it. Though I haven't tested the result.

Why not just use the desktop app?

**Comment by thomkeh** [comment]
I'll try to save the website and see.

> Why not just use the desktop app?

Because I have a Chromebook for which there is no desktop app. I also could imagine that this would be useful for Android tablets because the Android app doesn't have extensions.
