### ISSUE TITLE
in memory search

### ISSUE THREAD

**Issue by vesparny** [standardnotes/web#145]
Hi, first of all thanks a lot for such an inspiring and great project. I really appreciate the effort you are putting in.

Reading through the code I see the search happens in memory.
I suspect this would have a bad impact in terms of performance in case of a lot of notes.

Do you have any plan how to deal with this?

Thanks

**Comment by mobitar** [comment]
I don't think this is too big of a deal as even thousands of notes usually merely add up to 1MB.
