### ISSUE TITLE
Tags overlap with Trash

### ISSUE THREAD

**Issue by OriginalFannibal** [standardnotes/web#146]
I've  presently got around 30 tags, most of them nested as folders and since the Trash doesn't seem to dynamically adjust position, it overlaps with my tags. This makes selecting my tag/folder difficult and also  complicates moving tags into the trash.

**Comment by mobitar** [comment]
This is with the folders component? Can you post a screenshot? And perhaps this might be a better place to post it: https://github.com/sn-extensions/folders-component

**Comment by OriginalFannibal** [comment]
It is indeed with the folders component. I'll post it there then. Should this be closed then?

**Comment by OriginalFannibal** [comment]
Closing in favor of [issue opened at the relevant repository](https://github.com/sn-extensions/folders-component/issues/4).
