### ISSUE TITLE
Add Focus Mode

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/web#148]
Would be really great if a focus mode could be added as a new editor or even a component so that users could make use of it across all editors.

It would ideally make the app go full screen, put margins on both sides of the screen to center the text, and vertically center the line that you are typing currently. I guess I am just asking for [Zen](https://github.com/defunkt/Zen).

**Comment by mobitar** [comment]
You can already do this by clicking File under the note title, then Fullscreen.

**Comment by OriginalFannibal** [comment]
You mean Menu and then the Toggle Fullscreen option that appears? All that seems to do is hide the two sidebars (list of notes and tags).

I'm talking about something more along the lines of what you get with Zen in Atom. This is what it looks like:  

![screenshot from 2017-08-22 22-21-31](https://user-images.githubusercontent.com/20235646/29577218-2e5712ac-875a-11e7-9a4d-895dada22116.png)

The text view is centered with margins and the line that is currently being typed is centered vertically. Also, no menus of any kind. It is toggled with `Shift + F11`.

**Comment by mobitar** [comment]
You're essentially saying just hide the menus right? Because the screenshot above is what it looks like when I toggle Fullscreen in the app, then click the full screen button on the window. Except that it has the note title header on top.

**Comment by mobitar** [comment]
This is now available with the No Distraction theme.
