### ISSUE TITLE
macOS "hide" shortcut overridden in advanced markdown editor

### ISSUE THREAD

**Issue by wittjosiah** [standardnotes/web#150]
In the advanced markdown editor when focus is in the editor the `⌘+H` shortcut in macOS which is supposed to hide the window is used to create a header. The shortcut works when not focused on the editor window. I would suggest changing this shortcut, perhaps to `⌥+H` or `⌘⇧+H`.

**Comment by mobitar** [comment]
Thanks for the heads up. I'm not sure how easy this would be to change, but I'll give it a look. (This editor is based on https://github.com/sparksuite/simplemde-markdown-editor)

**Comment by wittjosiah** [comment]
@mobitar I still seem have this issue, was this closed as "won't fix"?

**Comment by mobitar** [comment]
Hey @wittjosiah, it was really closed as off-topic. I would have transferred it here but I can't transfer cross-account yet: https://github.com/sn-extensions/advanced-markdown-editor. Feel free to open the same issue there. For the record, I have had similar experiences with this editor hijacking some shortcuts. This editor isn't developed by us, so it's unlikely we'll make core changes to it.
