### ISSUE TITLE
Hide items with #archive (or other) tag

### ISSUE THREAD

**Issue by ChrisJefferson** [standardnotes/web#151]
This is related to a previously closed request -- #56 .

I use Standard Notes for projects I'm currently working on, and I'd like some way of hiding things which are finished, else I get swamped and can't keep track of the things I want. I think I just want some way of showing 'All' while hiding some tag (or tags).

I don't mind if we choose a special tag such as #archive or #finished, or have some way of hiding archived tags.

**Comment by mobitar** [comment]
I actually tried building this a few months ago thinking it would be easy, but a lot of obstructions happened. I was thinking the same thing: archiving a note simply adds an #archive tag. But it turns out it was a lot more complicated than that. I still plan on revisiting this at some point.

**Comment by mobitar** [comment]
Archiving is available in v2.
