### ISSUE TITLE
No Cursor on empty line in Advanced Markdown editor in Chrome

### ISSUE THREAD

**Issue by mchastainfm** [standardnotes/web#153]
Ive been noticing this for a while.  It is annoying.
![standard_notes_issue](https://user-images.githubusercontent.com/21045738/31293930-e28e8cea-aa8d-11e7-842f-27a49c7492df.gif)

**Comment by mobitar** [comment]
Hmm interesting. Do you know if it's always been like this? The thing about external editors is that they are based on open-source libraries, so fixing them isn't always trivial. This one in articular is based https://github.com/sparksuite/simplemde-markdown-editor.

**Comment by mobitar** [comment]
Can't replicate this anymore, possibly fixed in recent releases.
