### ISSUE TITLE
Themes do not theme the scroll bars

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/web#154]
On my system running Fedora 26, themes do not theme the scroll bar, which results in a less than optimal experience. This is the case irrespective of whether I am using the desktop app or the web app (on Firefox Nightly).

Here is a screenshot that shows what Futura looks like: 

![screenshot from 2017-10-07 07-15-30](https://user-images.githubusercontent.com/20235646/31309650-3d62179e-aba7-11e7-8fcd-e4cd1ade8c28.png)

**Comment by mobitar** [comment]
Fixed in recent release.
