### ISSUE TITLE
librejs firefox extension

### ISSUE THREAD

**Issue by JekoTronik** [standardnotes/web#155]
Hi !

As your application is Free Software (isn't it?), I thought I could connect to the app.standardnotes.org even with the librejs extension activated but the webpage doesn't load (it stays blank).

As I like browsing with this extension activated I would appreciate to see your web app running with it.

Cheers !

**Comment by mobitar** [comment]
I'm not familiar with librejs..could you explain the premise?

**Comment by JekoTronik** [comment]
Sorry I come back late. LibreJS isn't upgraded to be compatible with the new Firefox so, doesn't matter anymore...
Here are two links about LibreJS : 
* https://www.gnu.org/software/librejs
* https://addons.mozilla.org/fr/firefox/addon/librejs

Thank you for your work on StandardNotes.

**Comment by jspaetzel** [comment]
If I understand this correctly the addon basically just wants all of the js files that gets served to include a license header from the supported list: https://www.gnu.org/software/librejs/manual/librejs.html#Detected-Free-Licenses
Looks like the new license from https://github.com/standardnotes/web/issues/189 fits
