### ISSUE TITLE
Option for web app to not create new note before each login?

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/web#164]
Steps:
1. Open Standard Notes web app.
2. Standard notes creates new note with today's date.
3. I delete new note.
4. I log in and access my notes.

It's a minor annoyance, but it would be nice to be able to skip step 3.  Thanks!

**Comment by mobitar** [comment]
It shouldn't merge that note when you sign in. It should just vanish. Are you not seeing this behavior?

**Comment by kennethb22** [comment]
Nope. Once I login it shows the new note just below my pinned notes. Same thing in the Windows desktop app. See attached screen shots. 

![2017-11-16 14_15_35-notes standard notes](https://user-images.githubusercontent.com/19860067/32911475-4aa0f7b6-cada-11e7-8286-7962792ab849.png)

![2017-11-16 14_16_26-notes standard notes](https://user-images.githubusercontent.com/19860067/32911481-4d4c119e-cada-11e7-944e-44fcfd8a43d1.png)


![2017-11-16 14_26_01-notes](https://user-images.githubusercontent.com/19860067/32911485-51b2f162-cada-11e7-9b1c-9b2e57fe4cd3.png)

**Comment by mobitar** [comment]
Ah interesting, thanks I'll take a look. Also if I may ask, are you disabling the "Stay signed in" behavior often? Curious what your workflow is that you have to sign out/in often.

**Comment by kennethb22** [comment]
I prefer to not stay signed in on my computer at work.

**Comment by mobitar** [comment]
Should be fixed in recent releases.
