### ISSUE TITLE
Theme Rendering Delay

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/web#167]
I've created a simple theme that's accessible via this URL:  https://f001.backblazeb2.com/file/standardnotes44874/subtle/subtle.css?type=theme&name=Subtle

When I activate this theme in the web or desktop apps and open a note using the Simple Markdown editor, there's a slight delay (1 to 1.5 sec) before the theme is applied. When I open a note using system Plain editor, there's no delay in rendering with the theme.  The delay happens whenever I select a note that has the Simple Markdown editor activated. Would someone else try this theme and see if they get the same delay when using Simple Markdown? Is there something in the theme code that's causing this delay? Thanks!

**Comment by mobitar** [comment]
This is the nature of extensions. Editors are wholly separate from the core app, and are loaded remotely. After they are loaded, the active theme is sent to the editor, at which point it applies. So a ~1s delay will be normal.

**Comment by mobitar** [comment]
Oh I see, you're using external fonts in your theme. That will definitely increase the load time. None of our themes use external fonts.

**Comment by kennethb22** [comment]
Commenting out those external fonts fixed the issue. Thanks!
