### ISSUE TITLE
Text file import truncating note names from files with a period in the name

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/web#168]
Going through the notes I imported from text files, and discovered an issue. See attached screenshot of the Windows desktop app. It looks like the plain text importer doesn't deal well with periods in file names.  The highlighted note was imported from a file named "[Quote] - St. Ignatius of Loyola - Reforming the World". The text importer truncated the note name after the first period. You can see in the notes list below that it did this to a few other files that had the abbreviation "St." in the file name. Thanks!

![2017-11-20 16_39_40-](https://user-images.githubusercontent.com/19860067/33398454-020b1f34-d51d-11e7-81b3-3d15c4594900.png)

**Comment by mobitar** [comment]
Thanks, will look into this.

**Comment by mobitar** [comment]
We've done some work here in the last few years, so if this is still an issue feel free to re-open.
