### ISSUE TITLE
Highlight Search Results

### ISSUE THREAD

**Issue by BobTB** [standardnotes/web#171]
It would be very nice and helpful if search results would highlight in the editor windows. This could be a problem with all the different editor I suppose. 

But still, on longer notes, this is very helpful, for example I have a few hundred lines long notes. Interestingly chrome itself does highlight the string if I do second search from there, but this is making me search twice, first to find a note, and then to find the string in the note.

**Comment by mobitar** [comment]
Yup, totally agree. Hope to get to this soon.

**Comment by mobitar** [comment]
Highlighting is now available in desktop app.
