### ISSUE TITLE
Exporting notes makes a folder if the title has / in its name

### ISSUE THREAD

**Issue by BobTB** [standardnotes/web#172]
For example, I have **EBAY / Amazon tools** title for a note. When exporting it, I get all the notes in one dir, and there is a folder named EBAY with the note Amazon tools-60e1ab.....txt content in there.

**Comment by mobitar** [comment]
This is when you export into a decrypted zip right?

**Comment by BobTB** [comment]
Yes, decrypted zip.

**Comment by mobitar** [comment]
Should be fixed in recent releases.
