### ISSUE TITLE
Archived notes search does not work

### ISSUE THREAD

**Issue by isaacsu** [standardnotes/web#179]
I'm unable to use the search box to search for notes that have been archived. Is this by design, or a bug? Thanks.

**Comment by mobitar** [comment]
Ah good catch. Definitely a bug. Will get this fixed.

**Comment by isaacsu** [comment]
Thanks.

**Comment by isaacsu** [comment]
Received the fix - it works now, thank you!

**Comment by mobitar** [comment]
Great!
