### ISSUE TITLE
[Feature Request] Option to make archived notes read-only

### ISSUE THREAD

**Issue by isaacsu** [standardnotes/web#180]
Not sure if this is a common use case, but once I've archived a note, I would prefer not to be able to modify it. This means I can rely on it to not be accidentally modified or deleted. To modify it, I would expect to have to unarchive it, make the changes and archive it again.

It doesn't even need to be anything enforced in the data model, but just something on the client that has this behaviour would be sufficient. This would make me more likely to use Standard Notes as my note archiving tool of choice.

**Comment by mobitar** [comment]
Hmm it's not a bad suggestion. The only thing is, it's more code. On every platform. So I'll default to resisting it unless it's absolutely crucial.

Can you list any other apps that behave in this way, so I can get a feel for it?

**Comment by isaacsu** [comment]
Can't think of any that do that at the moment, sorry.

**Comment by isaacsu** [comment]
I guess perhaps the closest thing I can think of is how password managers work where there's a distinct `Edit` and `Save` step.
TBH with the e2ee functionality, I'd love to broaden my use of standard notes in that area.

**Comment by mobitar** [comment]
I do like the idea. And it would be easy to implement on desktop. But on mobile this requires some rethink of the composer, which I'm not sure is worth it currently. But will definitely keep on my radar.

**Comment by isaacsu** [comment]
>  But will definitely keep on my radar.
I wouldn't ask for anything more than that :) By the way, congratulations on the reskin of the desktop. It's looking good.

**Comment by mobitar** [comment]
Thank you!

**Comment by isaacsu** [comment]
Heya, I saw that you shipped the "locked notes" feature recently. That's so cool, I can't wait to go play around with it when i get a bit of time. Even on mobile? :mind_blown:

Thank you.

**Comment by mobitar** [comment]
Haha yup, available on mobile as well. Forgot to update this thread ;)
