### ISSUE TITLE
Link in sidebar to notes without label

### ISSUE THREAD

**Issue by adrm** [standardnotes/web#182]
To be able to organize my notes, I would like to have an automatic category that groups every note without tags.

**Comment by mobitar** [comment]
This is a popular request :) Hope to have something like this soon.

**Comment by adrm** [comment]
Great! Didn't see an open issue about this, feel free to close if this feature is being tracked anywhere else.

**Comment by mobitar** [comment]
This is now possible with smart tags: https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes
