### ISSUE TITLE
In note list view, all tags shown if a note has several tags

### ISSUE THREAD

**Issue by bnjbvr** [standardnotes/web#183]
I've got a note that has tags `A` and `B`. When I click on the tag `A` in the tags list (so as to filter only notes with tag `A`), all the notes don't show the tag `A` in their list of tags, except for this one note that has several tags. Adding a screenshot to make it more explicit:

![screenshot-2018-2-15 standard notes a private and secure notes app](https://user-images.githubusercontent.com/1180019/36261689-85c8643c-1265-11e8-8510-f3c595d588c0.png)

I'd expect the selected note to only show `#geek`, not `#associatif #geek`.

Does it make sense? Thanks!

**Comment by bnjbvr** [comment]
If you agree with my diagnostic, I'm happy to make a patch; it seems quite easy and I think I've found the right cutting points.

**Comment by mobitar** [comment]
True, it should probably do that. I'll make note of that. But the present logic of it is: If in All, show full string, if in tag, only show tags string if note.tags.length > 1.

A PR would be great!
