### ISSUE TITLE
"Extensions" button appears twice

### ISSUE THREAD

**Issue by AdamVig** [standardnotes/web#185]
![image](https://user-images.githubusercontent.com/5354752/36283823-b43f5b5a-1273-11e8-98c3-c471c96bd23d.png)

Version: 2.1.0
Platform: macOS 10.13.3

When clicked, both buttons yield fully functional extensions menus. They can even appear at the same time, one over the other, slightly offset in position.

**Update**
I also cannot apply themes on the web app. They work fine on the desktop app. I can toggle themes in the extensions modal in the browser and they change on the desktop app, but the web app theme stays on the default. I tested on Firefox and Chrome with the same results.

**Comment by mobitar** [comment]
The duplicate Extensions items can occur if you access the app on 2.1, then, access the app from another platform not running the latest version. So be sure you've upgraded on every platform, including mobile.

You can remove the duplicate manually for now by opening the Extensions menu that works, finding the "Extensions" item (you'll see two), and pressing Uninstall.

If you accidentally uninstall the working one, just refresh the page to try again. (It will reappear).

Regarding themes, that's strange. Can you try uninstall all your themes then re-installing?

**Comment by AdamVig** [comment]
Perfect, that works. I did upgrade everything, but must have upgraded them in the wrong order.

Uninstalling all of my themes and reinstalling/activating the one I wanted fixes the browser theme problem (on my work computer, at least).

Feel free to reopen if you have followup questions. Thank you for the quick response!

**Comment by mobitar** [comment]
Re-opening to make this easier to find.
