### ISSUE TITLE
[Feature Request] Variation of the simple task editor extension

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/web#188]
I had an idea for a chat-like interface a while ago, as someone who likes Twist's UI (but not their lack of using end-to-end encryption). 

I was thinking that maybe a good compromise to this would be to have an extension that uses the text input field from the simple task editor extension, but does not touch or alter the note content itself. This way the user does not have to scroll to the bottom of a note.

### Bonus Track
- Add the local/UTC date and time at the top, each time text is added, making it suitable for journal entries, followed the a hashtag of the the date. (e.g. #YYYYMMDD)

![Example of it being used](https://imgur.com/cCSti2v.jpg)

#### Key Differences between the existing and proposed extensions:
- New text input would be added to the bottom, not the top.
- There are no checkboxes, therefore not visibility options (of what to show or hide)
- Additional text might be added before each entry, such as a timestamp.

**Comment by grub-basket** [comment]
Yes, with the exception of it somehow adding the date for me, if possible.

And since the todo extension already exists, I figured that it would make this a bit easier to build for the most part.

**Comment by grub-basket** [comment]
You could look into Agenda’s UI for further inspiration, for the meeting notes idea.

**Comment by mobitar** [comment]
Don't anticipate any updates on this in the near future. Still a neat idea though.
