### ISSUE TITLE
Cannot sign in with Firefox ESR

### ISSUE THREAD

**Issue by Mikiya83** [standardnotes/web#190]
Hi,
I encounter a problem with Firefox ESR 52.7.0.
When a try to sig in, i fill in user/pwd, i click on "Sign In", but Generating keys failed, i get in console : 

`10:23:39,160 DOMException [OperationError: "The operation failed for an operation-specific reason"
code: 0
nsresult: 0x80530020] 1 compiled.min-86117b479c3a1eeeb16c32c8a83acecccb97f578a31a21fcc3d9211924004d9a.js:8:14443
	[1]</g</<.value/< https://app.standardnotes.org/assets/compiled.min-86117b479c3a1eeeb16c32c8a83acecccb97f578a31a21fcc3d9211924004d9a.js:8:14443
`

I find an issue on another project that may be related (TOR is affected but it is a fork from ESR so...)  : https://github.com/lesspass/lesspass/issues/213 with an error when webcrypto is used for pbkdf2 sha-256.

Firefox ESR is often use by companies so it's a shame if we can't use Standard Notes on it :/

**Comment by mobitar** [comment]
I have heard some reports of issues with ESR. Namely that offline storage doesn't even work (IndexedDB), so even if you logged in it might still not work. Are you able to save data offline?

**Comment by Mikiya83** [comment]
Yes, without being log, i can create new notes offline (not encrypted). If a reopen Firefox they are still there.

**Comment by mobitar** [comment]
It's hard to tell what that error is about. Any way you can dig up more clues? Is it failing at the network level, or some sort of internal issue?

**Comment by Mikiya83** [comment]
When a try to add a passcode offline, i get the same error in Console, so i think it's related to a local crypto process (key derivation for example).

**Comment by mobitar** [comment]
I can't replicate this on Firefox ESR 52.7.2 (64-bit). Adding a passcode succeeds for me. Signing in to my account also works. Only offline database doesn't work.

**Comment by Mikiya83** [comment]
:(
I'm on CentoOS 6 with the Firefox ESR 52.7.0, the version i get is not compiled by Mozilla but directly by RHEL team... i don't know, maybe they changed some "minor" things...

**Comment by Mikiya83** [comment]
I just tried on Firefox ESR 52.7.0 x64 on CentOS 7 and it works, i can log in...
So it's specific to Firefox ESR on CentOS 6, their changes break something :( i think you can close this issue.

**Comment by mobitar** [comment]
Hmm strange..

**Comment by Mikiya83** [comment]
The errors apparently occured here : 
`key: "generateSymmetricKeyPair",
                    value: function() {
                        var e = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : {},
                            t = e.password,
                            n = e.pw_salt,
                            r = e.pw_cost,
                            i = arguments[1];
                        this.stretchPassword({
                            password: t,
                            pw_salt: n,
                            pw_cost: r
                        }, function(e) {
                          var t = e.length / 3,
                                n = e.slice(0, t),
                                r = e.slice(t, 2 * t),
                                o = e.slice(2 * t, 3 * t);
                            i([n, r, o])
                        })
                    }`
-> sur " var t = e.length / 3, " -> "TypeError: e is null" 
and here : 
`{
                    key: "webCryptoDeriveBits",
                    value: function() {
                        var e = arguments.length > 0 && void 0 !== arguments[0] ? arguments[0] : {},
                            t = e.key,
                            n = e.pw_salt,
                            r = e.pw_cost,
                            i = arguments[1];
                        m.deriveBits({
                            name: "PBKDF2",
                            salt: this.stringToArrayBuffer(n),
                            iterations: r,
                            hash: {
                                name: "SHA-512"
                            }
                        }, t, 768).then(function(e) {
                            var t = this.arrayBufferToHexString(new Uint8Array(e));
                            i(t)
                        }.bind(this))["catch"](function(e) {
                            console.error(e), i(null)
                        })
                    }`
-> "console.error(e)" print : DOMException [OperationError: "The operation failed for an operation-specific reason"
code: 0
nsresult: 0x80530020]  
	[1]</g</<.value/<

**Comment by mobitar** [comment]
Yeah, must be a WebCrypto thing. Perhaps not supported fully by ESR?

**Comment by mobitar** [comment]
Please reopen if any new info or issue occurs with recent releases.
