### ISSUE TITLE
Note still shown after deletion

### ISSUE THREAD

**Issue by tjrana** [standardnotes/web#196]
I have found a bug where Standard Notes still shows a note after being deleted from a different device.

Steps:
1. Open Standard Notes on desktop; create a new note and add some content to the note; let the changes synchronize and quit the app
2. Open Standard Notes for iOS and delete the newly created note; let the changes synchronize and quit the app
3. Open Standard Notes on the desktop again; after the changes synchronize, notice that the note is deleted and removed from the notes list but the note still remains visible and editable; notice that edits made to the "deleted" note can still be synchronized

**Comment by mobitar** [comment]
Thanks, missed this.

**Comment by mobitar** [comment]
This should be fixed in the latest desktop version btw..

**Comment by tjrana** [comment]
@mobitar Yes, this seems to be fixed. I am going to close this issue. Thanks!
