### ISSUE TITLE
I can't enter application panel

### ISSUE THREAD

**Issue by emresaracoglu** [standardnotes/web#200]
Hi,

I installed the software without any problems but I can not enter the panel.

```
[root@localhost web]# rails s
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

What could be the problem?
Thanks.

**Comment by mobitar** [comment]
Not enough information here. What do you mean by panel?

**Comment by emresaracoglu** [comment]
I can not access this adresse (http://192.168.1.161:3000) with the Internet browser.

> The connection has timed out

**Comment by emresaracoglu** [comment]
```
[root@localhost web]# rails server -b 192.168.1.161
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://192.168.1.161:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://192.168.1.161:3000
Use Ctrl-C to stop
```

**Comment by mobitar** [comment]
There's nothing wrong with the output. This would just be a general Rails issue which I would recommend googling for. You want to be able to access your app at localhost or 127.0.0.1.

**Comment by emresaracoglu** [comment]
I spent a few hours but I could not find a solution.
I want to try it with the Docker. Standardnotes have a docker structure?

**Comment by mobitar** [comment]
Docker is indeed available. Please reopen if you continue to have issues.
