### ISSUE TITLE
Can't sign in: expired certificate

### ISSUE THREAD

**Issue by bocekm** [standardnotes/web#204]
Firefox won't let me go to the site _"The certificate expired on Monday, May 21, 2018, 6:49:50 PM. The current time is May 21, 2018, 7:19 PM."_
Chrome allows me to get in, but I'm unable to sign in: _"A server error occurred while trying to sign in. Please try again."_
I've installed the Windows client and it says the same as the web, server error.

**Comment by mobitar** [comment]
Sorry about that, should be fixed now. Something was causing our auto-renew script to fail.

**Comment by bocekm** [comment]
Thanks, the web works now. I can't attest that for the desktop client as I uninstalled it already, but I guess I can close the issue.
