### ISSUE TITLE
cloud agnostic sync

### ISSUE THREAD

**Issue by blackedtin** [standardnotes/web#206]
Please consider expanding the free option to use one's own cloud storage platform like digital ocean or amazon s3

**Comment by grub-basket** [comment]
You could self-host SN. https://standardnotes.org/developers

**Comment by mobitar** [comment]
Two way sync will have to require custom server code. No way around that. One can either self host, or for one way sync (backups), use the cloud providers we have integrations built for, or build their own integration.

**Comment by jmason888** [comment]
I see why two-way sync would require custom server code, but it seems like _backup_ (to s3, digital ocean, backblaze, whatever...) could be implemented as extensions.  (Either user-written or "official" extensions).

Does that sound right?

**Comment by mobitar** [comment]
Yeah, backups can definitely be made to anything that has an API. We'd like to add S3 in the future for both FileSafe and CloudLink.
