### ISSUE TITLE
[Suggestion/UX] Disable this extra bar

### ISSUE THREAD

**Issue by grub-basket** [standardnotes/web#207]
![image](https://user-images.githubusercontent.com/12993901/40818745-83d181f4-650d-11e8-8b01-bc77101ec757.png)

When I try to extend the middle panel or the editor, I sometimes mistakenly click on an additional bar, which I have yet to use on purpose. Please consider providing an option to disable this bar, or simply remove it. 

Thank you!

**Comment by mobitar** [comment]
Hmm..this bar is meant to resize editor margins. Can be useful in full screen. Has thrown a few people off. Perhaps an option to disable this can be useful. Will think it through..

**Comment by mobitar** [comment]
Can be disabled via note Options menu.
