### ISSUE TITLE
App installation breaks on windows when home path changes

### ISSUE THREAD

**Issue by pema1** [standardnotes/web#208]
OS: Windows 7 Enterprize
App version: standard-notes-setup-2.1.33

# Description

1. Standard Notes is installed on the computer
2. During reboot the home path of the user changes

   C:\users\Alice.001 -> C:\users\Alice

3. Standard Notes cannot be started or installed as the installer complains it could not overwrite 
  `Alice.001\AppData\Local\Programs\standard-notes\Uninstall Standard Notes.exe`

![image](https://user-images.githubusercontent.com/13132057/40846289-77b9c56e-65b9-11e8-8e56-4b9ef1b41734.png)

This situation occurs when you have a roaming profile and your not so favorite operating system fails to clean up after itself on shutdown.

How can I get Standard Notes to install without trying to uninstall the non-existing location first?

**Comment by mobitar** [comment]
Hmm that's a tricky one. We don't have much control over the installer, as we use a packaging solution.  It's best to handle this manually for now given how rare this is. If it becomes a bigger issue I can investigate a deeper solution.

**Comment by pema1** [comment]
Hi @mobitar, thanks for the info. As I have no administrative control over the machine how do you suggest to about this? Which configuration file should I adapt or delete?

**Comment by mobitar** [comment]
I'm honestly not too sure. Haven't run into this issue before. We use [electron-builder](https://github.com/electron-userland/electron-builder/issues) to package the app and create the installer. Perhaps there may be some guidance there?

**Comment by pema1** [comment]
The path was stored in the registry under

         HKEY_CURRENT_USER\Software\774f2290-3906-58eb-baae-35b0dc01c31e\InstallLocation

:open_mouth: 

If you modify this - and at least the user directory exists - the install works well :v:.

**Comment by mobitar** [comment]
Ah wow, glad you found a solution :)
