### ISSUE TITLE
Strip tags in the notes list?

### ISSUE THREAD

**Issue by vitormv** [standardnotes/web#210]
Hi, i noticed when I use the Plus Editor extension, the list of notes sidebar is still displaying the html code. Would it make sense to strip the html tags and use only a plain text summary?

<img width="1184" alt="screenshot 2018-06-13 14 48 31" src="https://user-images.githubusercontent.com/183328/41352154-e8d48618-6f18-11e8-98fe-04e8fadc08e2.png">

**Comment by vitormv** [comment]
Closed because this is already a very well known issue apparently. Sorry for the duplication.

**Comment by mobitar** [comment]
Haha no worries :) Glad you found the other tickets.
