### ISSUE TITLE
[Suggestion] Live Markdown without Markdown notation

### ISSUE THREAD

**Issue by daehruoydeef** [standardnotes/web#215]
What would it take to hide the markdown notation so that 
for e.g.
# "#" Heading 
becomes 
 # Heading

See typora or bear for a better understanding.

**Comment by mobitar** [comment]
I haven't found an open-source editor that does this. If you know of any let me know. I don't think we'll build this ourselves.

**Comment by daehruoydeef** [comment]
Thanks for your answer.

You can check out [Marktext](https://github.com/marktext/marktext) which is open source software and implements this feature.
Sadly I cannot highlight where the magic is happening in detail but I think such a feature would add great value to your Application and would make it more usable.

I do not know if this is to much of a hassle but typora and marktext also support inline latex which is really nice for study notes in general.

Thanks for your time and effort!
- Oskar

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by daehruoydeef** [comment]
Can you keep me up to date if this works out in the end? Do you ship the same application on desktop and mobile or would it be possible to just update the desktop version?

Keep up the great work!
- Oskar

-------- Original-Nachricht --------
An 10. Juli 2018, 18:27, Mo Bitar schrieb:

**Comment by mobitar** [comment]
New extension releases don't typically require extra work for mobile (mobile just uses the same web hosted infrastructure). Will try my best to update this thread but it's easy to lose track :)

**Comment by daehruoydeef** [comment]
Hey I just found this extension which also uses live markdown. Maybe this could help

https://github.com/plibither8/markdown-new-tab/blob/master/README.md

-------- Original-Nachricht --------
An 12. Juli 2018, 17:54, Mo Bitar schrieb:

**Comment by mobitar** [comment]
Interesting, I'll take a look.

**Comment by mobitar** [comment]
Still a neat idea, without any promising open-source projects. Not likely we'll develop this in house.
