### ISSUE TITLE
Private Standard File Server using Docker

### ISSUE THREAD

**Issue by fooness** [standardnotes/web#219]
Having followed every step in the [Deploying a private Standard File server using Docker](https://github.com/standardfile/ruby-server/wiki/Deploying-a-private-Standard-File-server-using-Docker) tutorial, we successfully got Standard Notes up and running.

Unfortunately, the last chapter [Using your new server](https://github.com/standardfile/ruby-server/wiki/Deploying-a-private-Standard-File-server-using-Docker#using-your-new-server) cannot be finished, as there is no such item in the account menu.

Could anyone please explain how to do this?

**Comment by mobitar** [comment]
The server option is now under Advanced Options in the Account menu: 

<img width="395" alt="screen shot 2018-08-03 at 9 37 38 am" src="https://user-images.githubusercontent.com/3277844/43648740-e351db86-9700-11e8-84a9-c0b6b3386d19.png">
