### ISSUE TITLE
Support for basic formatting

### ISSUE THREAD

**Issue by jamesrascal** [standardnotes/web#22]
Support for basic formatting Bold, italics, lists, H1, H2, Ideally in a WYSIWYG.

**Comment by levlaz** [comment]
@mobitar This seems like an excellent candidate for a plugin. Any third party editor you use, or one that you develop yourself will surely create some additional complexity and maintenance burden which goes against the goals of the project. 

I can imaging a plugin that (when installed) replaces the `editor-content` with any arbitrary editor provided by the plugin. 

[ProseMirror](http://prosemirror.net/), [ACE](https://ace.c9.io/#nav=about), and [Trix](https://github.com/basecamp/trix) come to mind.

**Comment by mobitar** [comment]
Right, this is a tricky problem. I definitely wouldn't want to implement these kinds of editors natively, since everyone wants what they want. I'm still thinking through a UI-based extension system (as opposed to the data extension system presently available), but it is a little more tricky. How do you envision a plugin working?

**Comment by jamesrascal** [comment]
A plugin system would be amazing for this. Having some sort of place where community members can upload a new plugin would be ideal.

**Comment by itnAAnti** [comment]
I agree with @levlaz that this would make a good plug-in. 

@mobitar, I don't have a suggestion on the architecture of a  UI-based extension system, but I can share how I would envision the plugin working if such an extension system existed:

* Only supports the formatting options from markdown, so file format remains unchanged.
* Eliminates the edit/read mode toggle. It always displays formatted, but is directly editable within the formatted view, (WYSIWYG, as @jamesrascal suggested)
* A formatting bar above the editor that displays the options (like most web rich editors)
* Support for standard OS-level hotkeys for bold, italics, underline.

**Comment by mobitar** [comment]
Editors solve this problem.
