### ISSUE TITLE
3 Questions

### ISSUE THREAD

**Issue by infosisio** [standardnotes/web#224]
1. I managed to solve the issue of removing html tags only in the list preview section by adding this Angular filter (I realize that this is not good for production but it works for me for the moment):
```
.filter('htmlToPlaintext', function () {
    return function (text) {
      return text ? String(text).replace(/<[^>]+>/gm, '') : '';
    };
  })
```

2. How would I redirect my local web version with modifications to the compiler that bundles this as a Linux executable so that I can test/use this as an App with my own modifications ? 

3. It would be nice if syntax highlighting was added for GDScript which is the main/official language of the Godot game engine that has gained wild popularity recently. A few projects like codemirror have already added this.

Thanks a lot !

**Comment by mobitar** [comment]
I believe you'd made some progress with [number 2](https://github.com/standardnotes/desktop/issues/210) already. Let me know if you still need help with it.

Feel free to submit a PR for number 3 :) Shouldn't be too bad to add a new language. https://github.com/sn-extensions/code-editor
