### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by infosisio** [standardnotes/web#225]
I'd like to ask, how scalable is the solution currently ? 

What if someone has thousands of notes for instance ? 

Is everything performing well, search included ? 

Would it help / be worth it, if search had to wait for enter to be pressed in order to not query tens of times, thousands of entries, upon every single character typed ?

**Comment by mobitar** [comment]
So far it hasn't been an issue. Some people use it with over 4000 notes and don't have any complaints. 

Optimization so far hasn't been a priority, but might be some way down the line.
