### ISSUE TITLE
Responsive Layout For Web Version

### ISSUE THREAD

**Issue by infosisio** [standardnotes/web#227]
This may be a rare scenario but I experienced it recently.

I wanted to use a friends phone to access my notes from app.standardnotes.org.

It is obvious that I couldn't ask him to install the app on his phone for me, so I headed to that site and I figured that you literally can't use it on small screens as the layout is not responsive.

Again, I know that this is a rare scenario but perhaps good to keep in mind.

**Comment by mobitar** [comment]
Yeah, known issue for now. Not sure if we'll optimize it as there's just too much going on, especially with extensions. But maybe one day.
