### ISSUE TITLE
File/Image uploading #feature-request

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/web#23]
Great work on StandardNotes!!

1 feature that would really help is to add image and files uploading/attaching

I would like to be able to
* embed an image in a note
* attach non image files to the note
* possibly add links to google-drive/dropbox/etc. like in Trello

Thanks!!!!!!!

**Comment by mobitar** [comment]
You can do this now via the File Attacher extension: https://standardnotes.org/extensions/file_attacher
