### ISSUE TITLE
Docker build files are missing batch and extensions manager

### ISSUE THREAD

**Issue by SomeGeek** [standardnotes/web#238]
As the title says: The docker build files are missing the extensions manager and batch manager.

When a image is built using the included instructions, the 'extension' tab gives a 404-error. I think this is not expected behavior?

**Comment by mobitar** [comment]
Docker support has so far been maintained by external collaborators, so can't speak to it. If you are familiar with it, then generally, you just need to make sure these two environment variables are set:

```
EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
```
