### ISSUE TITLE
sync.standardnotes.org TLS1.0 enabled

### ISSUE THREAD

**Issue by dddw** [standardnotes/web#239]
Hi,

Thanks for this great project. I'm slowly merging all my notes from multiple sources into standardnotes. 
Mainly because encryption is what I lack now in my current setup.
I'm did a quick SSL check on sync.standardnotes.org some months ago and it looked perfect, however TLS1.0 has been droppped recently.

[Qualys ssl labs analyze](https://www.ssllabs.com/ssltest/analyze.html?d=sync.standardnotes.org).

Also I'd like to mention the nice project [standardnotes-fs](https://github.com/tannercollin/standardnotes-fs), which is a great addendum!

**Comment by mobitar** [comment]
Thanks, I'll have to review our SSL status again soon. Disabling TLS1.0 might alienate older browsers, so I'll just need to make sure we don't hurt any users by doing this.

**Comment by mobitar** [comment]
Great, thanks for that snippet @PuffinBlue!

**Comment by mobitar** [comment]
Sorry, forgot to update this issue. TLS 1.0 had been disabled shortly after that last comment.
