### ISSUE TITLE
Remove tag from note

### ISSUE THREAD

**Issue by dyladan** [standardnotes/web#24]
I cannot see any way in the current UI to disassociate a note from a tag without deleting and recreating the note.

**Comment by mobitar** [comment]
So initially the app only supported one group per note. We later to changed it to tags, but haven’t gotten around to making the UI more taggy. But for now it’s drag and drop. I believe this should work: select the tag, then drag the note from the list into the All group. But having a better tags UI is definitely high on the list.

**Comment by dyladan** [comment]
Dragging into the 'all' tag did not seem to remove it from a different tag. Also, It should probably be made more clear that you can't edit and re-upload the JSON file to achieve this behavior. I suspect that the uploaded JSON is being merged in the standard file server rather than replacing entirely? But I am really quite unsure.

**Comment by mobitar** [comment]
Yes duplicates from an import are merged with your existing notes. That's a round about way of removing a tag though :) 

You're right, removing tags doesn't seem to be working. Will get a fix out for this asap.

**Comment by mobitar** [comment]
New tags UI is now live. Please give it a try and let me know what you think.
