### ISSUE TITLE
Icons Have Wrong Path in manifest.json

### ISSUE THREAD

**Issue by necopinus** [standardnotes/web#242]
App icons have the wrong path in `manifest.json`; since the icons are located in `/favicon` rather than `/`, the relevant section should be:
```
    "icons": [
        {
            "src": "/favicon/android-chrome-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/favicon/android-chrome-384x384.png",
            "sizes": "384x384",
            "type": "image/png"
        }
    ],
```
This is observable on https://app.standardnotes.org/, where trying to use the **Create shortcut...** option on Chrome OS fails to pull the app icon, and pulling up the application manifest in the development tools reveals that neither icon can be loaded.

**Comment by mobitar** [comment]
Ah thanks, will get this fixed.
