### ISSUE TITLE
Passcode confirmation when changing passcode

### ISSUE THREAD

**Issue by pshelly** [standardnotes/web#248]
This ensures that the one changing the passcode is owner of the notes and not a third party.

Solution Example:
Add a third box when changing the passcode, which takes as input the current passcode.

Keep up the awesome work!

**Comment by mobitar** [comment]
You're talking about the local passcode and not the account passcode, correct? If so, agreed. Will make a note of this.

**Comment by pshelly** [comment]
Yes the local passcode. 
![passcode1](https://user-images.githubusercontent.com/43761801/47867080-e33d8600-ddd6-11e8-89d4-71775cded8a4.png)
Basically any can click change passcode and lock the user out of the account.
![passcode2](https://user-images.githubusercontent.com/43761801/47867081-e33d8600-ddd6-11e8-8faa-2df918cf8aac.png)
A third box in this screen requiring the users current **local passcode** would solve the issue.

**Comment by mobitar** [comment]
Indeed, that would be useful. Thanks!

**Comment by mobitar** [comment]
Available in v3.

**Comment by pshelly** [comment]
It look really nice! Thanks for listening!
