### ISSUE TITLE
[Suggestion] Auto-Lock with passcode enabled

### ISSUE THREAD

**Issue by pshelly** [standardnotes/web#249]
This is a useful feature for locking the program when not in use. The program would lock itself depending on the configuration.

Possible configurations:
- Time without using the program (Timer begins X amount of time after last edit or view)
- Program put into background:
  If program is minimized or not in active display immediately lock the program.
- Combination of the two previous ones:
  If not in active display and X amount of time has passed lock the program.
- On system lock and sleep.

Solution Examples:
Add a third box to passcode lock with the auto-lock functionality

- KeepassXC supports most of these suggestions

**Comment by mobitar** [comment]
Please see here: https://github.com/standardnotes/forum/issues/295

**Comment by mobitar** [comment]
Autolock is implemented in 2.4.0-beta1, which you can download from here: https://github.com/standardnotes/desktop/releases/tag/v2.4.0-beta1

**Comment by pshelly** [comment]
Works perfectly thanks!
