### ISSUE TITLE
Delete a tag

### ISSUE THREAD

**Issue by dyladan** [standardnotes/web#25]
I cannot see a way to delete a tag. I would have expected to be able to export a JSON file, and upload a modified version, but this didn't work.

**Comment by mobitar** [comment]
You can select "File" in the notes list of the selected tag. I agree, this needs to be more clear.
<img width="453" alt="screen shot 2017-01-17 at 8 05 36 pm" src="https://cloud.githubusercontent.com/assets/3277844/22048066/52ac98bc-dcf0-11e6-8e88-33f4230d174b.png">

**Comment by dyladan** [comment]
ah thank you
