### ISSUE TITLE
[Request] Add MD5, SHA256, and SHA512 Checksums to the Downloads Page

### ISSUE THREAD

**Issue by redrosa** [standardnotes/web#250]
Also perhaps sign the package with a GPG key. Standard Notes is great and I highly recommend it to everyone. But adding a simple "this is what you should get when you calculate the checksums in a terminal to ensure it was not modified by an attacker" would be great since one of Standard Notes' main selling points is privacy and security and it wouldn't take more than 5 or so minutes to do.

**Comment by mobitar** [comment]
Apps are already signed for Mac and Windows. If we do custom signing, it would only be for Linux.

**Comment by mobitar** [comment]
Grouping into https://github.com/standardnotes/web/issues/216
