### ISSUE TITLE
Filter by tag in archive

### ISSUE THREAD

**Issue by MatthewScholefield** [standardnotes/web#253]
I have most of my notes archived in an attempt to speed up load times (Still takes 1-2 seconds), so it would be nice to be able to find archived notes by tag. Would this be a reasonable feature to implement?

Thanks.

**Comment by mobitar** [comment]
Archiving notes wouldn't have any impact on performance I'm afraid. It's just a UI level feature that hides notes from your main lists. You have have archived notes show up by selecting "Archived Notes" from the "Display" section in the "Options" menu of the middle notes panel.

**Comment by MatthewScholefield** [comment]
@mobitar Whoops, didn't even notice that options menu, thanks! Just curious, is it suggested to just delete notes once you get a few hundred? I have about 500 notes and it makes startup feel laggy with everything getting generated into the UI for the first 2 seconds. I'm probably just being too picky though :).

**Comment by mobitar** [comment]
Not necessarily. You may just have some abnormally large notes. I have over a thousand notes with no issues. I've heard from people who have a few thousand with no issues. It really just depends on the capability of the devices you use + the size of your individual notes (i.e, make sure you don't have one note that is like 70,000 words—that would really slow you down).
