### ISSUE TITLE
Attachment Support

### ISSUE THREAD

**Issue by hypery2k** [standardnotes/web#258]
Besides the [attachments plugin](https://github.com/standardnotes/web/issues/89) is there an option to directly add attachments? Maybe on a self hosted notes server?

**Comment by mobitar** [comment]
You can create a custom integration for FileSafe, such as your own server: https://github.com/standardnotes/filesafe-relay/tree/master/app/lib/integrations

Then self-host the FileSafe relay server.

**Comment by mobitar** [comment]
Correct, no built in server file storage. Requires 3rd party cloud storage like Dropbox or Nextcloud.
