### ISSUE TITLE
Self-Hosting: Replacing localhost with local IP address

### ISSUE THREAD

**Issue by smartspacemonkey** [standardnotes/web#259]
Hi,

I have successfully set the app along with the ruby server where it is accessible through `localhost:port`.
Unfortunately, the app doesn't show up when I enter the local IP address (i.e `192.168.1.xx`) instead of `localhost`.

Any reasons why this isn't working ?

thanks.

**Comment by bryvin** [comment]
When running the web app with "rails s" add on "**-b 0.0.0.0**" and see if that works. Sometimes you have to bind to that port for it to work properly.. I've never read into why this is but I know it's worked for me in scenarios like this.
