### ISSUE TITLE
Allow for Tabs 

### ISSUE THREAD

**Issue by levlaz** [standardnotes/web#26]
Its nice to be able to add some simple structure to notes with the use of tabs. Since there is no "submit" button (i.e. everything is always syncing) then there is no real reason to switch focus out of the TextArea when entering the tab key. 

This is pretty easily accomplished using `PreventDefault()`. 

I would be happy to implement this if I get a +1 :)

**Comment by mobitar** [comment]
Yes go for it :) That was actually on my list so a pull would be awesome.
