### ISSUE TITLE
Use relative dates & Shorter default date format

### ISSUE THREAD

**Issue by christianhans** [standardnotes/web#260]
In the sidebar: Instead of displaying the full date and time underneath each note, why not display a relative timestamp if applicable? E.g. Today, 8:12 am instead of Saturday, Dec 08 2018, 8:12 am. Other examples:

Yesterday, 12:10 pm
2 days ago, 12:10 pm
3 days ago, 12:10 pm
12/04/18, 12:10 pm

Note the last example, instead of displaying the currently used much longer date format, default to a shorter version if the date is longer than 3 days ago.

**Comment by mobitar** [comment]
We're not using any external datetime libraries, which would be required to do something like this.

**Comment by christianhans** [comment]
I see. Would that cause any problems?

**Comment by mobitar** [comment]
Would integrating a third party library cause any problems? Just adds dependencies. Too many dependencies make the application more difficult to maintain over time.
