### ISSUE TITLE
Sort found notes by relevance

### ISSUE THREAD

**Issue by christianhans** [standardnotes/web#266]
This issue applies to both Web/Desktop and Mobile. Currently found notes are sorted by date modified. Often times the note I'm looking for is the very last modified. This makes it hard to find notes. Other note taking applications sort by relevance, for example when words in the note's title match it should have a higher relevance.

**Comment by mobitar** [comment]
Notes are always sorted by your current global sort order. So you could change your sort order while you're performing a search. Sorting by relevance could be interesting, but not sure that's well defined for how simple the search function currently is.
