### ISSUE TITLE
Tab followed by Ctrl-Z does not work in Firefox

### ISSUE THREAD

**Issue by rosscanning** [standardnotes/web#268]
100% reproducible using Firefox, on Windows 10 or Linux, with no plugins necessary.

Repro:

1. Select some text.
2. Press tab. Text is replaced with a tab, as expected.
3. Hit Ctrl-Z to undo. Nothing happens.

Does not happen with Chrome on Windows 10. Have not tried any other browser.

**Comment by mobitar** [comment]
I believe I've seen someone mention this issue before. Not much we can directly do, since the undo behavior comes out of the box for HTML textareas. Will keep an eye out to see if something can be done.
