### ISSUE TITLE
Unsupported AngularJS

### ISSUE THREAD

**Issue by sorin-davidoi** [standardnotes/web#269]
`angular@1.6.x` is [no longer being developed](https://docs.angularjs.org/misc/version-support-status) (not even bugfixes and security patches) and it currently has two [XSS vulnerabilities](https://snyk.io/test/npm/angular/1.6.1). What are the short-term and long-term plans regarding this?

**Comment by mobitar** [comment]
Long term, we're looking to move to React, sharing components across our current React Native mobile app. Short term, we'll look to update to Angular 1.6.9.

**Comment by sorin-davidoi** [comment]
> We believe in building software that lasts.

Maybe it would be worth looking into using Web Components (without any frameworks) so that a rewrite won't be necessary again.

**Comment by shreeshbhat** [comment]
Web Components using Stencil would be great!

**Comment by mobitar** [comment]
Upcoming 3.0.4 release will use Angular 1.6.9.
