### ISSUE TITLE
Wrong IVs in CBC thwarts your security model

### ISSUE THREAD

**Issue by AnomalRoil** [standardnotes/web#27]
I'm curious about this part of your code:
https://github.com/standardnotes/web/blob/master/app/assets/javascripts/app/services/helpers/crypto.js#L42
```
  encryptText(text, key) {
    var keyData = CryptoJS.enc.Hex.parse(key);
    var ivData  = CryptoJS.enc.Hex.parse("");
    var encrypted = CryptoJS.AES.encrypt(text, keyData, { iv: ivData,  mode: CryptoJS.mode.CBC, padding: CryptoJS.pad.Pkcs7 });
    return encrypted.toString();
}
```
More specifically by the `var ivData  = CryptoJS.enc.Hex.parse("");` part.
You are using CBC mode, which security **crucially** relies on the use of _unpredictable IVs_.

From what I've tested, `CryptoJS.enc.Hex.parse("");` produces an empty WordArray and, from my tests, passing it to `CryptoJS.AES.encrypt` results in a **completely predictable IV**, namely the all-zeros one.

This means notably that two same plaintexts encrypted with the same key will be encrypted into the same ciphertext, so the server may do some evil pattern analysis on those and get information out of it.

**Comment by mobitar** [comment]
The reason we use blank IVs is because every item is encrypted with a random key, that essentially serves as an IV. So no two items are ever encrypted with the same key. This makes implementation simpler across platforms.

**Comment by AnomalRoil** [comment]
Okay. 
I've just found [your models](https://standardfile.org/models), I'll read it.

If this is the case, this is not an issue.

**Comment by asdfghkk** [comment]
I don't get it. You're still encrypting the random item keys using the static master key with no IV, thus leaking data.

**Comment by mobitar** [comment]
True, I was talking only about encrypting the content. Hadn't considered encrypting the item key. But if the item key is random, and every user's encryption key is different, what exactly can be leaked?

**Comment by mobitar** [comment]
I guess this answers the question: http://crypto.stackexchange.com/questions/8600/why-should-i-use-an-initialization-vector-iv-when-i-have-unique-keys

It doesn't completely break security, but it's better to have. I'll begin working on incorporating IVs.

**Comment by mobitar** [comment]
Here are details on the proposed solution: https://github.com/standardnotes/android/issues/70
