### ISSUE TITLE
Searching then clicking tag clears search but leaves highlighting

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/web#271]
In the Windows app, a certain search workflow will cause the search field to be cleared but highlighting to remain (until another search is done):

1) Search for any term that returns results
2) See which tags are used among all of the notes in the search results
3) Click on a tag that is used
4) Search field gets cleared, but the highlighting will remain until another search is done.

Seems like expected behavior would be to either not clear the search field or to get rid of the highlighting once another tag is clicked.

Related: https://github.com/standardnotes/desktop/issues/238

**Comment by mobitar** [comment]
Fixed in upcoming 3.0.10.
