### ISSUE TITLE
Simple Task Editor note Preview changes after title change

### ISSUE THREAD

**Issue by agba55** [standardnotes/web#273]
Notes created using the Simple Task Editor have this nice "Notes preview", that displays "x / y tasks completed" followed by a completion bar followed by a list of tasks. 

However, this Simple Task Editor notes preview changes to standard text, if you modify / edit the note title via the web interface. Instead of the above preview, it displays " - [ ] task 1 - [ ] task 2 - [ ] task 3"

I've replicated this with different notes / tags using steps:

1. Create note
2. Change editor to Simple Task Editor
3. Add 3 new tasks - in the notes preview list it correclty displays "0 / 3 tasks completed"
4. Change the title of the note
5. The notes preview changes to - [ ] task 1 - [ ] task 2 - [ ] task 3

**Comment by mobitar** [comment]
I can't replicate this. It sounds like you may be using an older version of the desktop app. Please make sure you're up to date and try again. I believe this issue was explicitly fixed in a previous release. Please re-open if you see this behavior persist in the latest version.

**Comment by agba55** [comment]
sorry, this still happens in 3.0.4 .. desktop client indeed

**Comment by mobitar** [comment]
Was just able to replicate this by pressing enter/return on my keyboard in the title field. That might have been what you were doing. Originally I was just testing by modifying the title without pressing enter.

**Comment by mobitar** [comment]
This issue should be fixed (forgot to update this thread, so not sure which release it was).
