### ISSUE TITLE
Self hosting db:migrate doesn't work

### ISSUE THREAD

**Issue by MansoorMajeed** [standardnotes/web#274]
I was following the doc [HERE](https://docs.standardnotes.org/self-hosting/self-hosting-with-ec2-and-nginx), but `rails db:migrate` is failing. The task itself is not found. 

```
rails db:migrate
rails aborted!
Don't know how to build task 'db:migrate' (see --tasks)
/usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.1.0/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.1.0/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.1.0/lib/rails/command.rb:46:in `invoke'
/usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.1.0/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

How do I get this working? (I'm using phusionpassenger + Nginx for production use)

**Comment by mobitar** [comment]
DB migration is for the Standard File data server. For the web app, there are no migrations, so you don't need to do this step.

**Comment by MansoorMajeed** [comment]
Sorry, i think i misunderstood. I thought "web" was the file server. If i
were to setup self hosted standard notes, which instructions should I
follow?

**Comment by mobitar** [comment]
To set up the [syncing server](https://github.com/standardfile/ruby-server), follow these instructions: https://docs.standardnotes.org/self-hosting/self-hosting-with-ec2-and-nginx

**Comment by MansoorMajeed** [comment]
Thank you so much.. I'll give it a shot. :)
