### ISSUE TITLE
Docker development environment

### ISSUE THREAD

**Issue by vtambourine** [standardnotes/web#28]
Docker can be very handy for developers as it allows them to easily setup and teardown the application with all its dependencies without worrying about version or db conflicts and everything.

If you don't mind, I can setup more or less default Docker config for Ruby.

**Comment by mobitar** [comment]
Yes please, go for it :) Docker would be great.

**Comment by mobitar** [comment]
Closing this until someone volunteers to do it.

**Comment by swayson** [comment]
I wouldn't mind creating this. But my node.js knowledge is seriously lacking. If somebody could add some information as to how to install node.js along with all the dependencies and these other build tools like grunt etc. that would be great. I did an attempt but the [README](https://github.com/standardnotes/web/blob/master/README.md) was a bit sparse.

**Comment by mobitar** [comment]
You would essentially just follow these instructions but sub in the web repo, and install just a couple dependencies:

```
sudo yum install nodejs npm --enablerepo=epel
npm install grunt
```
