### ISSUE TITLE
New note button and new tag button "+" vertical alignment is off

### ISSUE THREAD

**Issue by jmichaels** [standardnotes/web#283]
![Capture](https://user-images.githubusercontent.com/5171869/55857744-eeda6900-5b3b-11e9-832d-4465a257697d.PNG)

![Height to top](https://user-images.githubusercontent.com/5171869/55857961-7de78100-5b3c-11e9-82cc-258a4f0e3f8c.PNG)

![Height to botton](https://user-images.githubusercontent.com/5171869/55857975-82139e80-5b3c-11e9-8e4e-7d780c79399a.PNG)

The alignment on the "+" in the "New Note" and "New Tag" buttons is skewed a bit towards the bottom.

These are very important and prominent buttons, so I think this small fix would go a disproportionately long way towards making the app feel more polished and reliable.

**Comment by jmichaels** [comment]
Ah, okay - that makes sense.

Two other possible solutions, which could have side benefits for streamlining development:

(I apologize in advance if you've already ruled these out for good reasons, I don't have a lot of backstory/context on the design decisions)

- Use an icon font to standardize icons.  I like Font Awesome, not sure if the license would be compatible though
- Include a font(s) with the app, to standardize the look and behavior across platforms.  This could alleviate a lot of similar headaches, but maybe you're trying to avoid bloat, or are prioritizing using native fonts?

**Comment by mobitar** [comment]
Icon font for those buttons is a good idea. We already use a custom one for the lock button and the sort reverse button. I believe it's a custom built ionicons pack.

**Comment by shreeshbhat** [comment]
Using SVG icons might be easier and better.
https://css-tricks.com/icon-fonts-vs-svg/
