### ISSUE TITLE
Click on lock symbol does not lock

### ISSUE THREAD

**Issue by hillbilly3456avk** [standardnotes/web#284]
When I hover over the lock symbol in the lower right corner and click as soon as the symbol gets the focus (changes color) without pointing to the symbol directly, the app would not lock. Need to point to the symbol to activate the lock.

**Comment by mobitar** [comment]
Good catch, fixed in https://github.com/standardnotes/web/commit/6835331664628be089e866e52a63b1f7ab5390d4.

**Comment by hillbilly3456avk** [comment]
Wow that was fast! Thanx
