### ISSUE TITLE
Note cursor jumps to the end if typing <TAB>(key)(key) quickly

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/web#286]
When in a note on the Windows app, hitting <TAB> (as if to create an indent in the note) followed quickly by two other keys (for example "<TAB>xx" or "<TAB>--") causes the two last keys to disappear and the cursor to jump to the end the note.  If you then type an additional key, the scroll position will jump to the end as well.

This is in version 3.0.6, using the plain editor, with an account, on a stable network.

Previously created: https://github.com/standardnotes/desktop/issues/236

**Comment by DBCerigo** [comment]
Can confirm I get same issue/behavior using web app in Safari (v11.0.3). 

(As well as confirming this is also a slight but common hinderance to my current usage. Web-dev not my forte so won't attempt to investigate myself - gl with it though!)

**Comment by mobitar** [comment]
Thanks for the confirmation @DBCerigo. This one is scheduled for investigation for the next release.
