### ISSUE TITLE
Modify favicon to match app icon

### ISSUE THREAD

**Issue by ashfaq92** [standardnotes/web#287]
Hi, Standard note is loved for its platform in-dependency.  But, in Windows PC and Android, its icon is just like and executing command line application. But on web app, its favicon is reversed 'U'. Please make its icon same on all platforms (and better) so that it avoids confusing users.

**Comment by mobitar** [comment]
Indeed, the favicon on the web app is using the base standardnotes.org favicon. We can update this to reflect the application icon instead.

**Comment by mobitar** [comment]
Adjusted in latest release.
