### ISSUE TITLE
Remove the shortcut 'ctrlKey + e' for 'clickedEditNote'

### ISSUE THREAD

**Issue by dreamszl** [standardnotes/web#29]
It has a conflict with mac's original shortcut for line-end.

**Comment by mobitar** [comment]
I wasn't aware of this shortcut. Doesn't seem to do anything for me in native Mac apps. Is this the same behavior as pressing cmd + right arrow?

**Comment by mobitar** [comment]
Ah ctrl+e, not cmd+e. The shortcut in the SN Mac app uses the cmd key though and not ctrl. Are you seeing conflicts?

**Comment by dreamszl** [comment]
Yeah, same behavior as pressing cmd + right. By the way it's a emacs shortcut supported by mac, so I used it very frequently. 

The mac app seems also has the conflicts.

**Comment by mobitar** [comment]
Cool, I'll take a look at this when I revisit shortcuts, which seem to be in very high demand :)

**Comment by mobitar** [comment]
Fuxed
