### ISSUE TITLE
Implementing extra extended features like 'Speech to text', 'convert to PDF' and Image uploader

### ISSUE THREAD

**Issue by Mistakili** [standardnotes/web#291]

**Comment by Mistakili** [comment]
<h4>Components</h4>
<p>Standard Notes is a free open source privacy multi-purpose note application available on Web, and for download on most widely used devices such as Windows, Mac, Linux, Android, and IOS.</p>
<blockquote class="wp-block-quote"><p>Standard notes application is the most equipped note editor with a focus on privacy and other interesting extended features. It is no doubt that the best of Standard notes features are only accessed through the extended version, these features simply make our interaction with the app convenient and comfortable.<br>My idea is to further increase the usability of the Standard notes app by adding to the features of the extended version.</p>
</blockquote>
<h4>Proposals</h4>
<h4><em>Recommended:</em></h4>
<ol><li><strong><em>Speech-to-Text</em></strong><br><strong><em>Understanding that the only option available for users on most note applications as it relates to entering of words into the note editor is through the keyboard, I will like Standard Notes to provide an alternative means like implementing the Speech-to-Text technology in the extended version of the application.</em></strong></li><li><strong><em>Convert to PDF</em></strong><br><strong><em>Before I started using the Standard notes app, there were other functions I had to combine in other applications before my article became ready for publishing. I had different applications that allowed me to edit my notes in markdown format, generate image URL of a picture and converted the notes to PDF file.<br>However, since using the Standard notes app has saved me the stress by combining a ton of awesome features together in one place, I will like that Standard notes also offer the option to convert written notes to PDF from within.</em></strong></li><li><strong><em>Image URL generator</em></strong><br><strong><em>This feature enables images to be converted to URL so it can display when submitted online. A picture is worth a thousand words is a common phrase to most writers, the need to add pictures to articles is very important, knowing this, writers like myself have to switch between applications to generate URL's for the intended images while writing which could be distracting and very inconvenient. With this feature, users can easily upload their intended image which will automatically generate the URL right from within the app so that the article can be completely ready for publishing without leaving the app.</em></strong></li></ol>
<hr class="wp-block-separator" />
<p><sub>Implementing the speech to text feature</sub></p>
<img src="https://steemitimages.com/640x0/https://cdn.steemitimages.com/DQmXny4LYngHFHbAuogaaNW2P67vY5tNV6NT6QbLjGxm8iT/bng.png" alt="bng.png" />
<hr class="wp-block-separator" />
<img src="https://steemitimages.com/640x0/https://cdn.steemitimages.com/DQmR4RjaiG5LR8S77AaCLapZr2oy35ZuXqdyycs1WaznZq6/bng.png" alt="bng.png" />
<p><sub>Implementing the Image upload and convert to pdf function.</sub><br></p>
<h4>Benefits</h4>
<p>Standard notes application stems to be the go-to privacy notes application, providing users with security and amazing features that they usually had to combine two to three other note applications before they could get. It is very uncommon to see an all in one notes application with a Speech-to-text function, whereas, it is very useful and underrated. A lot of time, I've wanted to write down an idea but couldn't because my hands were occupied, sometimes, when I eventually free my hands, the idea disappears even before typing the second line, but if I could speak the idea into my phone and my speech is turned to text, that would be amazing.</p>
<p>Users of Standard notes app are more likely to be people who engage heavily with writing every day and as such have different purposes for writing, some require more professional outlook for their articles which mean they have to convert their works to the PDF file format. I find myself in this category of users, which means I have to go out of the app before my article can be ready to be published. I will appreciate if the Standard note app includes this feature and reduce the stress for users who need to convert their written notes to an alternative format like PDF.</p>
<p>From the writing of articles to excerpts to blogs and even jotting of ideas, there is none that can deny the importance of images. They simply add more taste to our work. Whether they be our pictures or stock images gotten from the internet. Integrating a feature that allows users to upload images and generate the URL is definitely a key feature that will increase the apps ease of use and eliminate the need for users to switch between apps.</p>
<h4>Conclusion</h4>
<p>Standard Notes app is known for its privacy and hyper-rich features in its extended version. It is the fastest and best all in one note app with a very simple interface. Standard notes extended features offer users the functions they have to combine multiple apps to perform all in one place. However, there is room for improvement and with the highlighted suggested features, I think Standard notes will become far ahead in usability, customer satisfaction and mode of operation compared to other note apps and will becoome the ultimate app of choice when it comes to note editing applications.</p>
 <br /><center><hr/><em>Posted from my blog with <a href='https://wordpress.org/plugins/steempress/'>SteemPress</a> : http://steemhosting.com/kilimanjaro/implementing-extra-extended-features-like-speech-to-text-and-convert-to-pdf-in-standard-notes-app/ </em><hr/></center>

**Comment by mobitar** [comment]
Hey @Mistakili, thanks for the detailed proposal. I like some of these ideas, but we have to be careful how we tackle complex features like this. I think I can confidently say that for the core version of Standard Notes, we're done adding features to it. Anything new we add will try to be in the form of an extension, to avoid code and interface pollution.

For speech to text, I think we'd mostly rely on the OS for this behavior. An editor extension that would try to implement this behavior would likely need to make an external network request to process the speech and get text, so there might be a privacy barrier there. 

For convert to PDF, this would be nice to have. Definitely something that would be a prime candidate for an extension to implement, for example, the Action Bar. The only issue is how it would anticipate the different formats users can edit in SN, like Markdown, or HTML, or Tasks, or whatever future format comes about. So some architectural considerations needed here.

For file attachments and images, this is something we already do with [FileSafe](https://standardnotes.org/filesafe). The Bold Editor was also recently released, which integrates with FileSafe to allow embedded images in the editor.

**Comment by Mistakili** [comment]
Thanks for the reply...awesome work...great app
