### ISSUE TITLE
Better font in web in plain editor

### ISSUE THREAD

**Issue by siddhugolu** [standardnotes/web#292]
The web font is not consistent with the system font, which is contrary to the android app. I'm attaching a screenshot for both. Please take a look.

Web:
![image](https://user-images.githubusercontent.com/9106868/58366134-6c282600-7ebd-11e9-9821-29a36431ee6d.png)

Android:
![image](https://user-images.githubusercontent.com/9106868/58366158-c4f7be80-7ebd-11e9-9d01-e7379561d54b.png)

**Comment by mobitar** [comment]
It looks like you have Monospace enabled on the web. Press Options > Monospace to toggle. Otherwise, each platform will use its own system font, so there will be differences in appearances between operating systems, as we don't use custom fonts.

**Comment by siddhugolu** [comment]
Oh neat! That solved the issue. Thanks :)
