### ISSUE TITLE
Deleting/trashing a placeholder note should not convert that note into a real item

### ISSUE THREAD

**Issue by ElCoyote27** [standardnotes/web#296]
Hi,
First time I'm reporting this but this is not a new issue per se and it happens on most platforms (Desktop - Linux RHEL7, Web).. Whenever I browse around 'categories', a 'Note 1' comes up sometimes and I have trouble getting it rid of it (a new note comes back if I continue using SN).
It's a little bit annoying because I like to keep my notes clean and tidy, but....

**Comment by mobitar** [comment]
Thanks @ElCoyote27, have accepted this issue under the web repo. Will get this fixed in a future release (not 3.0.10, most likely).

**Comment by mikaa123** [comment]
Hey there! I came to say that I also experience this issue. Basically, every time I'm on a tag or view that doesn't have previous notes, it adds a placeholder note. And then whenever I trash it, it comes back up.

**Comment by mobitar** [comment]
This has been fixed in a previous release.
