### ISSUE TITLE
cursor keys not working correctly after unlock with passcode

### ISSUE THREAD

**Issue by MustachedMario** [standardnotes/web#307]
After unlocking SN with a passcode and clicking somewhere in any plaintext note, there is no way to move the cursor up/down with cursor keys, left/right is working.

- unlock SN with a passcode
- UI is rendered
- cursor has no focus on anything at this point
- you have to click in a note content to get cursor focus
- no way to move cursor up/down, but left/right with cursor keys
- moving cursor by left clicking in the same note, doesn't change behavior
- clicking any other note and back, or changing browser tab an back, cursor keys working as expected

I'm using latest firefox with no extension or adblocker etc., currently I am not able to test this with other browser. Seems related to the event system that seems not to be triggered after UI is finish rendering.

**Comment by mobitar** [comment]
Is this issue still happening? I believe I read elsewhere that this was using the Minimal Markdown Editor. Or if you have a pinned tab in Firefox, this could happen, and you would need to reload. Please re-open if you're still experiencing this.

**Comment by MustachedMario** [comment]
Yeah this is still an issue. In my case, this is happening without any editor, pure plaintext.
After unlocking with passcode and clicking inside the first automatic selected note, the cursor keys are not working.

I tested this again and found a strange behavior:
In the situation where cursor keys are not working (e.g. up/down), and I still hammering the cursor keys up/down, the cursor is working after around 30 up/downs.

It seems to me, that are UI events in queue that needs to finish to process.
If this is the case, this is also the main reason for all my reported bugs the last months.
It seems all is related to that. (e.g. missing sorting of notes, missing tags, missing counters...)

**Comment by mobitar** [comment]
Hmm, in that case, it's likely that your app is still loading local data? Pay attention to the footer at the bottom when you first start the app. It will say "Decrypting xx/xx"—this is a computationally intensive process. If you are running a computer with low resources, it might freeze up the UI until it's done. Regarding missing counters, be on the lookout for v3.3, which is releasing soon, which should hopefully fix this issue.
