### ISSUE TITLE
Option to set Markdown Preview as default open mode.

### ISSUE THREAD

**Issue by jamesrascal** [standardnotes/web#31]
Have an option to set preview mode as the default after a note is created. Currently, it defaults to edit mode. I use notebooks as a reference and read from my notes more frequently than I write.

When I open a note that uses image embed or formatting I only see the markdown text until switching to preview mode:

![markdown](http://i.imgur.com/5UlEEW0.png)

Having the preview mode as default would be ideal.

**Comment by gabrielcossette** [comment]
I agree as well. Even making it the default would be suitable IMO. Only a double-click is needed to switch to edit mode.

**Comment by amtsh** [comment]
@gabrielcossette I feel the same. Created a PR https://github.com/standardnotes/web/issues/54
@mobitar What do you think?

**Comment by mobitar** [comment]
See comment in PR.
