### ISSUE TITLE
Use localized date string for last refresh date

### ISSUE THREAD

**Issue by CapitolRadio** [standardnotes/web#314]
As I am not from America, I find it quite annoying always reading the date of my notes wrong when the month is positioned in first place instead of the day. Would it be possible to have the ability to switch this around in preferences? Or would that mean switching the order for EVERY Standard Notes user by default?

**Comment by mobitar** [comment]
Ok thanks, I'll take a look at this. If anything I'll at least attempt to make it more consistent with other dates.

**Comment by CapitolRadio** [comment]
Thanks a lot Mobitar!
