### ISSUE TITLE
Unable to sync across devices

### ISSUE THREAD

**Issue by siddhugolu** [standardnotes/web#324]
Unable to sync across devices after making any edit. The problem is replicated across all the platforms that I've been using (Android, web, and Windows). Attaching a screenshot of the error that I'm getting on windows app:
![image](https://user-images.githubusercontent.com/9106868/69040950-b9bcc000-0a14-11ea-9050-44270062b146.png)

**Comment by mobitar** [comment]
Should be back up now..
