### ISSUE TITLE
Sync Failure 

### ISSUE THREAD

**Issue by DBCerigo** [standardnotes/web#325]
```
There was an error while trying to save your items. 
Please contact support and share this message: 
TypeError: undefined is not an object (evaluating 'n.saved_items.map')
```

On Safari v13.0.2. 

Started today/yesterday - no upgrades of Safari in that time, been on v13 for a while now.

Getting multiple errors in Console. E.g. `Auth hash does not match, returning null.` (I'm successfully logged in.) `Origin https://app.standardnotes.org is not allowed by Access-Control-Allow-Origin.` etc.

**Comment by jbeldia** [comment]
Users have been experiencing sync issues across their devices for the past couple of hours

https://github.com/standardnotes/forum/issues/770

As far as I know, the devs are still looking into the issue, hopefully it will be fixed soon!

**Comment by JulBor25** [comment]
It should be fixed now. At least for me.
