### ISSUE TITLE
[Feature Request] MathML or Latex Support

### ISSUE THREAD

**Issue by brunoalano** [standardnotes/web#33]
Should be nice to have support to LaTeX or MathML on the editor.

**Comment by mobitar** [comment]
This would come in the form of an editor extension, but details on those are still TBA. I'll update this ticket as details develop.

**Comment by brunoalano** [comment]
Anyway to I do that Editor Extension by myself?

**Comment by mobitar** [comment]
The system for editor extensions hasn't built yet. Are you saying you'd like to architect the system?

**Comment by brunoalano** [comment]
I thought that the Editor Extensions engine was built. I can build it, but probably won't be the best structure

**Comment by mobitar** [comment]
No not built yet. Soon hopefully.
