### ISSUE TITLE
Cannot import extensions using the "Import Extension" input box and pressing Enter

### ISSUE THREAD

**Issue by Ruin0x11** [standardnotes/web#334]
I tried to import a theme using the `Import Extension` link in the webapp and got no response or indication it worked. (I'm using Extended.)

1. Open [app.standardnotes.org](https://app.standardnotes.org) and log in.
2. Open `Extensions` and click `Import Extension`.
3. Paste in the JSON URL of the extension and press Enter. Nothing happens.

The theme I want to install is this one: https://cdn.jsdelivr.net/gh/orestarod/sn-themes/theme-installers/lyons.json

I tried another theme, but it also didn't work: https://static.swalladge.net/sn-themes/better-solarized-dark/package.json

I'm using Chrome 78 as the browser.

**Comment by bryvin** [comment]
This is an issue with the CORS and what resources are allowed to be requested by outside sources (other than the Host itself). Any server or host that is intended to be used to host an SN extension should have at least the following rules:

```
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Origin: *
```

You can verify this is an issue by checking your browsers console after hitting enter when trying to import these URLs you will see errors that complain about the CORs policy.

**Comment by saegl5** [comment]
Tip: If you are hosting an SN extension on GitLab or GitHub, though, try hosting its css stylesheet on GitLab Pages or GitHub Pages. Nothing would happen after installing my custom theme/extension, either, unless I hosted the stylesheet on GitLab Pages. GitHub Pages should work, too.

Example using the GitLab Pages/Hugo template:
Place [stylesheet name].css in [project name]/themes/beautifulhugo/static/css/, and push changes to the server;
In Standard Notes, for the "my-extension.json" note, set "url": "[baseurl]/css/[stylesheet].css", and update the private post;
Reinstall the custom theme/extension.

...There is probably an easier alternative, but this one worked for me.

**Comment by saegl5** [comment]
Example using GitHub Pages:

Create a remote empty public GitHub repository, and name it: \
`[username].github.io`

Upload [stylesheet].css

Update the url address in [my-extension.json](https://docs.standardnotes.org/extensions/publishing#steps): \
`"url": "https://[username].github.io/[stylesheet].css"`
