### ISSUE TITLE
Scenario when unable to create a new note

### ISSUE THREAD

**Issue by mereg0** [standardnotes/web#336]
**Repro steps**

1. Make a new account that has no notes.
2. There will only be the "Note 1" placeholder note.
3. Toggle to either "Archived" or "Trash" views
4. Toggle back to "All Notes" view
5. Attempt to create a new note using the "+" button
6. No new notes can be created until page reload and recreation of "Note 1" placeholder note.

**Comment by bryvin** [comment]
Thanks for pointing this out, I confirmed this is happening and we will look into fixing this behavior.
