### ISSUE TITLE
Unable to download backup, JavaScript errors

### ISSUE THREAD

**Issue by pcrockett** [standardnotes/web#345]
At app.standardnotes.org, when I first visit the website, but before typing in my local passcode, I notice in the developer console two errors. The first error is a content security policy error:

> Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

The second error is a TypeError:

```
TypeError: "this.leftResizeControl.setLeft is not a function"
    loadPreferences https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:23
    value https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:23
    $broadcast https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:15
    value https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:25
    value https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:25
    value https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:7
    r https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:15
    completeTask https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:15
    r https://app.standardnotes.org/assets/javascripts/app-38726368277adf9321d5a8fb723a272725b51f565c9140bc2caa646c22479f00.js:13
```

However these errors don't seem to cause any problems for me as I normally use the app. They may be entirely unrelated to my _real_ problem, which I encounter when trying to export a backup. When clicking the _Export Backup_ button in the sidebar, nothing happens except this log in the developer console:

> ReferenceError: SFItemParams is not defined

This error seems to happen regardless of whether I'm trying to download an encrypted or unencrypted backup.

I'm on Firefox 71.0 (64-bit), OS is Manjaro Linux.

**Comment by mobitar** [comment]
Can you try signing out of your account then signing back in, or, signing into a new browser session, and see if that makes a difference?

**Comment by pcrockett** [comment]
I did. I even created a brand new Firefox profile from scratch, with default settings and without any extensions. I also tested today with the same version of Firefox on a different Windows machine. Weird behavior is still there.

Jan 6, 2020 4:48:38 PM Mo Bitar <notifications@github.com>:
