### ISSUE TITLE
Website and sync server are both down right now

### ISSUE THREAD

**Issue by user8446** [standardnotes/web#355]
Maybe a status page, something on twitter, or notice on github would be a good addition for the users.
 Update: Everything is back starting late Fri 1/24/20. Was down all day

**Comment by mobitar** [comment]
This is the only report we received of this. Might have been a local issue.

**Comment by user8446** [comment]
@mobitar 
Odd, I tried two different networks and even tried an alternate DNS at the time.
A status page would be great a great addition to communicate to the users.
Thank you
