### ISSUE TITLE
Can't create new note inside View

### ISSUE THREAD

**Issue by christianhans** [standardnotes/web#369]
1. Select any view from sidebar (e.g.`!["Todo", "ignored", "or", [["content.title", "includes", "TODO"],  ["content.text", "includes", "TODO"]]]`)
2. Click on New Note button
3. Note is created but immediately deleted

v.3.3.2 - macOS

**Comment by mobitar** [comment]
Hmm, do you mean deleted as in doesn't appear in the list anymore? Because testing this, the note is created, and I can continue working on it, but is just removed from the list if it doesn't satisfy the View criteria. For example if it doesn't include TODO, it won't include it in the list.

**Comment by christianhans** [comment]
So I have several views. One view is

**Comment by baptiste-grob** [comment]
Thanks for the video. I can reproduce the issue on my end. Will look into it

**Comment by christianhans** [comment]
Thanks guys, works great now!
