### ISSUE TITLE
Unit, Integration, Acceptance Tests 

### ISSUE THREAD

**Issue by levlaz** [standardnotes/web#37]
So I noticed that this app (and several others in the org) don't have any tests yet. Are you planning on implementing some tests? 

If so, would love to help. 

If no, would love to do it. 

I work at a CI company, so no tests make me sad. ;)

**Comment by mobitar** [comment]
Yes, tests are great for longevity! Would love your help. Feel free to take a stab at it.

**Comment by fdhoff** [comment]
If you get something started @levlaz , I will help contribute to the tests.

**Comment by levlaz** [comment]
Awesome thanks @mobitar 

Also, @fdhoff will send a PR today to get a basic test framework up and running. Appreciate the help!
