### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Joseph-PS** [standardnotes/web#374]
<img width="1212" alt="Screenshot 2020-02-18 at 22 50 47" src="https://user-images.githubusercontent.com/60518474/74763337-a46e6080-52a5-11ea-9c86-feccbebc6c6d.png">

Using two plural words together is grammatically incorrect. The best practise is to use the first word in singular and the consecutive word in plural.
The verb "allow" should be in singular to agree with the word system (singular)

**How it should be:** End-to-end encryption is a system of encryption that **allow parties** to communicate in a way that severely limits the potential for third-parties to eavesdrop on or tamper with the messages.

**Comment by mobitar** [comment]
Good catch! Fixed. cc @theodorechu
