### ISSUE TITLE
Search through "All notes" won't find results from "Archieved"

### ISSUE THREAD

**Issue by danielmanesku** [standardnotes/web#399]
I have a note with content "test" and I archive this note. If I do search from "All notes" with keyword "test", this note won't show up in results.
Is this by design? If it is, can you please add an option to enable search everywhere, including Archived notes?

**Comment by baptiste-grob** [comment]
Thanks for your feedback! We're designing version 4 of the app right now which will change how search works. To say in what capacity would be premature, but I'll tag @zsoltszilvai in case he had not considered this use-case yet :)

**Comment by mobitar** [comment]
In the notes list, Options > Display > Archived Notes will display archived notes in your current view.

**Comment by danielmanesku** [comment]
Thanks for confirming that this is on your radar! 
@mobitar thank you for this tip, I'll do this until version 4 is released.
