### ISSUE TITLE
Unable to connect to standardnotes.org

### ISSUE THREAD

**Issue by hl2guide** [standardnotes/web#403]
I live in Australia and I'm no longer able to sync or connect to standardnotes.org (web or app).

![1](https://user-images.githubusercontent.com/17044982/81775602-7c06a300-9530-11ea-8a3b-bac0842f5edc.PNG)

Anyone else having issues?

**Comment by JaspalSuri** [comment]
I'm sorry that you're currently unable to connect to Standard Notes. 

One of my friends in Australia was able to connect to the site.

Have you updated your firewall or hosts file recently?

**Comment by hl2guide** [comment]
The only change has been a security update for Windows 10.

**Comment by hl2guide** [comment]
Just did a tracert and it seems like an ISP issue at the moment, I'll let you know if I make progress.

**Comment by hl2guide** [comment]
Made some progress, turned out it was a my router chasing it's own tail. Rebooted it and all fixed up. Thanks for the help though.

**Comment by JaspalSuri** [comment]
I'm glad to hear that! Thank you for keeping us updated!
