### ISSUE TITLE
Sync fails when using Edge Chromium?

### ISSUE THREAD

**Issue by hl2guide** [standardnotes/web#427]
When I access https://app.standardnotes.org using Edge Chromium any Sync attempt fails:

![1](https://user-images.githubusercontent.com/17044982/87109973-50dace80-c2a9-11ea-80ee-c001a349ded3.PNG)

![2](https://user-images.githubusercontent.com/17044982/87109980-546e5580-c2a9-11ea-9e92-ee8eb2e6425e.PNG)

The DevTools Console says:

`Access to XMLHttpRequest at 'https://sync.standardnotes.org/items/sync' from origin 'https://app.standardnotes.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
`app-=========.js:15 Request error: `
`regeneratorRuntime.async.c.abrupt.regeneratorRuntime.async.onreadystatechange @ app-=========.js:15`
`sync.standardnotes.org/items/sync:1 Failed to load resource: net::ERR_FAILED`
`app-=========.js:15 Sync error:`
`Uncaught (in promise)  app.standardnotes.org/:1`

It has no DevTools Console errors when I use SRWare Iron (another Chromium browser).

**Comment by JaspalSuri** [comment]
I currently don't run into any issues with Edge Chromium on macOS. We were having issues when performing some server-side upgrades several hours ago today. Can you try signing out and clearing your cache before signing in again to see if it works? Does it work in a private browsing session on Edge?

> It has no DevTools Console errors when I use SRWare Iron (another Chromium browser).

Thanks for letting us know! I haven't used that browser in years!

**Comment by hl2guide** [comment]
seems to be fixed now.
