### ISSUE TITLE
Autolock occasionally locks while actively typing in a note

### ISSUE THREAD

**Issue by IceFire23** [standardnotes/web#456]
**Describe the bug**
I have autolock set to 5 minutes. There have been a number of sporadic cases where the autolock will trigger while I am in the process of actively typing in a note. In the past I've also seen cases where it locks when I'm pretty sure the app wasn't idle for 5 minutes, but those are less clear-cut than the recent case I had where it locked while I was in the middle of typing a word.

**To Reproduce**
Unfortunately have not figured out how to reproduce the scenario or what the common theme between occurrences is.

**Expected behavior**
Autolock should not trigger while I'm typing into app since I've set it to 5 minutes.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909
 - Standard Notes Version: 3.4.2

**Additional context**
I've seen these cases occasionally over many months. It's not common but it has happened a number of times.

**Comment by JaspalSuri** [comment]
Hi, I'm sorry that both of you have experienced this bug several times. Please be assured that it's on our list of things to fix! 
#406

**Comment by IceFire23** [comment]
That's good to hear! Also, I just wanted to check - I saw this was transferred to the web forum, but all the times I've seen this issue have been on the desktop app (I haven't used the web app).

**Comment by JaspalSuri** [comment]
It should be fine. In my report for this bug in our internal boards, I've made sure that the distinction has been made just in case. 🙂

**Comment by baptiste-grob** [comment]
Hey there, this problem is now fixed thanks to https://github.com/standardnotes/web/commit/9036beb3f370a95c2d190754bd1009658c01cdeb. It will be deployed to the web app momentarily and included in the next version of the desktop app 👍

**Comment by IceFire23** [comment]
Thanks!
