### ISSUE TITLE
Secure Spreadsheets web: number of rows is limited to 79?

### ISSUE THREAD

**Issue by BasilTomato** [standardnotes/web#466]
In the Secure Spreadsheets web application there is only 79 rows available.
If I move the cursor into a cell in the last row (A79) and try to insert more rows (menu: Insert tab, Add row below) an error message appears: "Cannot insert row below the last row."
If the last row contains any data and I try the add new row action a different error message appears: "Cannot insert cells due to data loss possibility. Select another insert location or delete the data from the end of your worksheet."

Is it possible to increase the row limit to something more realistic? 79 rows is extremely limited for any productive work.

**Comment by BasilTomato** [comment]
OK, this seem to be a know issue: https://github.com/standardnotes/secure-spreadsheets/issues/13

**Comment by mobitar** [comment]
You can still add more rows. Just select the second to last row and add rows then. Clear any surrounding data temporarily if it gives you any trouble.

**Comment by BasilTomato** [comment]
OK, thanks!
