### ISSUE TITLE
Allow deletion of tags

### ISSUE THREAD

**Issue by royalharsh** [standardnotes/web#49]
Currently, I don't see any options to delete tags in the web version.

**Comment by mobitar** [comment]
You can delete a tag by pressing "File" in the notes list with the tag selected.

**Comment by royalharsh** [comment]
It deletes the note but not the tag. :confused:

**Comment by mobitar** [comment]
Wrong column. In the middle column. 
<img width="359" alt="screen shot 2017-01-22 at 12 36 29 pm" src="https://cloud.githubusercontent.com/assets/3277844/22184825/69005268-e09f-11e6-9e60-fabf559d19c2.png">

**Comment by royalharsh** [comment]
Thanks! :smile:
