### ISSUE TITLE
Issue with loading of extensions

### ISSUE THREAD

**Issue by Alfavio** [standardnotes/web#491]
**Describe the bug**

After I start the app, for all extensions I get the message *"There is an issue loadind [name of extension]"*. This bug appeared recently. The app work correctly not log ago.

![Screenshot from 2020-10-31 13-34-52](https://user-images.githubusercontent.com/5478075/97779377-e8786b80-1b7d-11eb-8c22-cf858c8b7e16.png)

**Steps done to try fix the issue:**
- update the app
- sing out and then sign in
- reinstall the app

**Machine:**

OS: Arch Linux
Version: v.3.4.10
Package: [standardnotes-desktop](https://aur.archlinux.org/packages/standardnotes-desktop/)

**Additional context**
I have valid extended subscription.

**Comment by dmuiX** [comment]
I think I have solved it on the client side:
The Extension Bold Editor was causing this error. If you could make it to the extension setting page it is showing some message like this extension is causing some error and you could deactivate it.
I it is is caused because they have introduced a new Bold editor and the old one is still active. Maybe the devs can do something about that on the server side respectively on the code of the extensions?

**Comment by dmuiX** [comment]
okay have to withdraw it:
Error ist still there. Maybe it is caused by another extension. I will try to deactivate token vault and report.

**Comment by Alfavio** [comment]
I tried uninstalling both the Bold Editor extension and also the TokenVault, but the issue persists.

**Comment by dmuiX** [comment]
Don't know why but in the web application on edge/chrome its working for me now. On the Desktop Version there is still an error: It stopps decrypting the notes on 400. And in Firefox it just flickers all the time. But the decryption is working. Though its not usable

**Comment by dmuiX** [comment]
And it doesn't matter if the exensions are installed or not. => No Difference respectivly the same result: Working on edge/chrome, not working in firefox and desktop app (on mac)

**Comment by baptiste-grob** [comment]
Hey @Alfavio, are you using the community AUR package? We've had reports of it not working correctly recently.

**Comment by Alfavio** [comment]
@baptiste-grob Yes, I'm using the community AUR package without an issue until now.

**Comment by baptiste-grob** [comment]
Can you try the AppImage or the Snap and report back? https://github.com/standardnotes/desktop/releases

**Comment by Alfavio** [comment]
I tried the AppImage and it works correctly. Thank you!

**Comment by baptiste-grob** [comment]
Nice! Happy to see you got it sorted out.
