### ISSUE TITLE
Unable to access my notes

### ISSUE THREAD

**Issue by siddharthsyal** [standardnotes/web#492]
I signed into Standard notes (web) but was not able to access my notes. The application just displays "This note is awaiting its encryption key to be ready. Please wait for syncing to complete for this note to be decrypted.". I tried to authenticate into iOS device but the same issue persisted. Can you please help with this.
![Notes_·_Standard_Notes](https://user-images.githubusercontent.com/40547786/97890632-c3116c00-1cfb-11eb-970c-63976bf3d978.jpg)

**Comment by mobitar** [comment]
Hi @siddharthsyal, are you using a self-hosted syncing server by any chance? If so you will need to upgrade that.

Otherwise, if you're not, can you try opening app.standardnotes.org in a new private Chrome/Safari window, and sign into your account from scratch, and see what the result is?

**Comment by siddharthsyal** [comment]
Hi @mobitar , I authenticated into the web application but I receive the same error message _("This note is awaiting its encryption key to be ready. Please wait for syncing to complete for this note to be decrypted.")_. Also, when I authenticate into the application, I get an error message about encryption. I have attached the screenshots for both of them.

I started getting this issue after I upgraded the iOS application to v3.5.0.

![Standard_Notes___Web__1](https://user-images.githubusercontent.com/40547786/97908810-34114d80-1d15-11eb-8d32-6d9b53624c1d.jpg)
![Notes_·_Standard_Notes](https://user-images.githubusercontent.com/40547786/97909057-966a4e00-1d15-11eb-96f7-dea18d32f67b.jpg)

**Comment by JaspalSuri** [comment]
Hi @siddharthsyal,

Thanks for letting us know that this has been fixed with v3.5.2 of the iOS app (over email). I'm closing this for now, but please don't hesitate to reach out to us or re-open this thread if needed in the future. 🙂
