### ISSUE TITLE
App fails to start on *BSD

### ISSUE THREAD

**Issue by prcmt** [standardnotes/web#494]
Tried accessing app.standardnotes.org from an OpenBSD machine today and got a plain white screen.

The javascript console gives this error:
```
Uncaught (in promise) Error: Platform must be supplied when creating an application.
```

It looks like this might be the fault of [`getPlatformString`](https://github.com/standardnotes/web/blob/0630957ef092ef2c4a3411b456e722ffa9d8fad9/app/assets/javascripts/utils.ts#L3) not handling the case of `navigator.platform` not containing either `mac`, `win`, or `linux`.  For instance, `navigator.platform` returns "OpenBSD amd64" for me.

**Comment by baptiste-grob** [comment]
Good catch, thanks for the report!

**Comment by prcmt** [comment]
Thank you for the quick fix!
