### ISSUE TITLE
[bug] - Tab key inside of a note goes to the end of document 

### ISSUE THREAD

**Issue by levlaz** [standardnotes/web#50]
See [here](https://github.com/standardnotes/web/pull/42/files#r97437269) for details. 

Sorry.. I have no idea why handling tabs is so complicated. :)

**Comment by levlaz** [comment]
@mobitar just reporting this here in case someone else notices this issue, I will send a PR with a fix.

**Comment by mobitar** [comment]
Oh wow didn't even realize that, but you're right.

**Comment by levlaz** [comment]
Yeah, I use the app every day now and ran into this. The good news is I can only blame myself. :D

**Comment by djhalliday** [comment]
Thanks for looking into this @levlaz, I've started using the app every day and this is definitely one of the most maddening bugs!

**Comment by levlaz** [comment]
@djhalliday my pleasure! I totally agree that this was driving me crazy as well. I am also sad that I shipped this bug. :) 

I submitted a PR that fixes this. Thanks so much for bearing with it.

**Comment by mobitar** [comment]
I also noticed that I couldn't shift + tab from the textarea to go back to the title. Do you think that's an easy fix?

**Comment by levlaz** [comment]
Yeah for sure, we can add a condition to not fire this off when shift is pressed.

**Comment by levlaz** [comment]
@mobitar I updated the PR to handle Shift + Tab with the browser default.
