### ISSUE TITLE
"Please upgrade to the latest version of Standard Notes to sign in."

### ISSUE THREAD

**Issue by dasTor** [standardnotes/web#507]
I have set up the webapp and did host it successfully.
I am on the master branch and everythigs works. Now i have updated my syncing server,
and have carelessly updated my account to v004.

Now i can't sign in the webapp, it just says:

"Please upgrade to the latest version of Standard Notes to sign in."

**Comment by dasTor** [comment]
nevermind, empty cache was the solution

**Comment by JaspalSuri** [comment]
Thanks for letting us know! Sorry that you ran into this issue in the first place.
