### ISSUE TITLE
Sort notes by last-updated or created-at

### ISSUE THREAD

**Issue by djhalliday** [standardnotes/web#51]
Currently sorts notes by created-at only. I usually have a small number of notes that I use as long-running logs over time, and these get buried unless I'm able to sort by last-updated.

**Comment by mobitar** [comment]
+1. I think this qualifies as an "essential" feature. Will try to get to it myself (probably sometime next week), or if someone else wants to take a stab at it..

**Comment by levlaz** [comment]
The easiest way to do this IMHO is to always sort by updated_at and then set updated = created when the note is first created. I just solved this same exact issue in [another app that I use](https://github.com/kanboard/kanboard/pull/2950).

**Comment by levlaz** [comment]
Took a peek into this, it looks like the `notes` model implements the `item` interface. However, I do not see any  case where `updated_at` is being updated. In fact, if I spit out `note.updated_at` in haml it shows the same value as `created_at`. 

So I think the scope of the work is a little bit larger than just sorting. 

@mobitar is setting `note.updated_at` as a part of `changesMade` not appropriate?

**Comment by mobitar** [comment]
`updated_at` is set by the server when changes are saved. We can set it locally, but it won't be saved by the server.

**Comment by levlaz** [comment]
I see, that explains why I was not seeing changes since my local dev environment is not syncing with a server.

That's great then, this should be as simple as setting orderBy on the ng-repeat, will try it out soon.

**Comment by mobitar** [comment]
Done
