### ISSUE TITLE
Unable to login with latest develop

### ISSUE THREAD

**Issue by cyberb** [standardnotes/web#522]
I am trying to package latest version of Notes Web / Standard Files for self-hosting and I am not able to login after a successful registration.

Web: version is latest develop (https://github.com/standardnotes/web/commit/1852b5e0454efe7aac369fd43201f6ff1037c405)
Files: https://github.com/tectiv3/standardfile/releases/tag/v0.5.0
Node for building web: v10.23.3

Error message: `Invalid email or password`
Code: 401

Does this mean Files is not compatible with latest Web or latest Web is not working?

I am doing this because some users complained that new version of desktop app breaks their existing (previously working) Notes based on:
Files: https://github.com/tectiv3/standardfile/releases/tag/v0.4.1
Web: https://www.npmjs.com/package/standard-notes-web/v/3.0.8

**Comment by baptiste-grob** [comment]
Hey @cyberb, I don't know about this standard file implementation but ours has been deprecated for more than a year now and we use [syncing-server](https://github.com/standardnotes/syncing-server) instead, which also has support for self-hosting 🙂

**Comment by cyberb** [comment]
I see, is there any migration path for data from SF to SyncServer?

**Comment by mobitar** [comment]
The new server should be backward compatible, but tbh I don't recall exactly this usecase. My recommendation would be to first create a database backup (or local data backup if it's just one account), then upgrade the server to see how it goes.
