### ISSUE TITLE
Resize grabber intercepts scrollbar intent

### ISSUE THREAD

**Issue by hlascelles** [standardnotes/web#533]
When trying to scroll the list of notes using a mouse, the act of moving over the right half of the scrollbar causes the resize grabber to suddenly appear, intercepting the click.

ie, about half the time I try to scroll the list using the scrollbar, I unintentionally end up resizing the panel.

Screenshot of the grabber doing the overlay: 

![image](https://user-images.githubusercontent.com/299102/110204164-95832d80-7e69-11eb-9ed2-00504c5da990.png)

Here is the Chrome panel highlight, showing the overlay.

![image](https://user-images.githubusercontent.com/299102/110204308-3bcf3300-7e6a-11eb-905b-a3a0fed8acb4.png)

Here is how wide the scrollbar is when I do not mouse over it:

![image](https://user-images.githubusercontent.com/299102/110204173-acc21b00-7e69-11eb-9593-a8ef2999c1dc.png)

OS: Mint Linux
SN Version: 3.6.0

The element concerned is `<panel-resizer collapsable="true" control="self.panelPuppet" default-width="300" hoverable="true" on-resize-finish="self.onPanelResize" panel-id="'notes-column'" class="ng-isolate-scope hoverable"><div class="panel-resizer-column"></div></panel-resizer>`

I could have a go at a fix if you have an idea how you'd like this approached. However I understand on Macs there may be a different solution.

**Comment by virtuallyvlad** [comment]
This used to be much worse years back, but I suppose it could still be improved somewhat.  Maybe the scrollbar could be shifted to the left, so that these two elements don't overlap.

Similar:
https://github.com/standardnotes/desktop/issues/222

**Comment by JaspalSuri** [comment]
Hi everyone, sorry for the delayed response. We're already aware of this issue (#582), but I've reached out to the dev team on this and will provide an update when I hear back.

**Comment by JaspalSuri** [comment]
Hi everyone, this was fixed in `v3.8.6` of the web and desktop apps. Feel free to let us know if you have any additional questions and/or feedback!

**Comment by hlascelles** [comment]
Fantastic, works great, thanks!
