### ISSUE TITLE
Decrypted individual notes missing in zip file

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/web#537]
In reviewing my decrypted zip file after export, I noticed I was missing over 100 notes in the `Items\Note` subdirectory. The notes did appear in the `Standard Notes Backup and Import File.txt` file. So this problem only affects the individual files generated for each note.

The notes that failed to export as an individual file all had one of the following reserved Windows File name characters in their title:

- asterisk `*`
- greater than `>`
- less than `<`
- question mark `?`
- pipe `|`

Removing these characters from the title resulted in the notes exporting correctly. Evernote adds the pipe character to some titles when adding a note using their web clipper so this was in quite a few of my notes.

In addition, the double quote `"` caused an error when unzipping. The note was exported but with the double quote character in the file name. This causes a `0x80070057 The parameter is incorrect` error. I use this character a fair amount for denoting inch measurements.

Finally, the forward `/` and backward `\` slashes are removed while colon `:` is replaced by a space in the file name. I don't mind the space but I use forward slash in dates. Removing the `/` converts a date like `2014/12/01` into `20141202` in the file name. I would prefer to see a consistent replacement for all special characters whether that is a space ` ` or perhaps an underscore `_`.

**Comment by JaspalSuri** [comment]
Hi @lnolan5017, sorry for the delayed response. Thanks for taking the time to create a separate issue for this. I've assigned this to our web and desktop app dev for review.

**Comment by baptiste-grob** [comment]
Hey @lnolan5017, thank you for reporting this issue, we're in the process of fixing it and will let you know once we're done!

**Comment by JaspalSuri** [comment]
Hi @lnolan5017, version 3.6.6 of the web and desktop apps have been released and should address this issue as the notes with special characters in their titles are exported successfully & contain underscores in place of each special character. 
![image](https://user-images.githubusercontent.com/44656000/114531048-639b7e80-9c00-11eb-85bb-8f0fd6499c2d.png)

**Comment by lnolan5017** [comment]
I have updated and confirmed that it is working fine now.

I also noticed that you now limit the file name to 100 characters including
the extension. This solved another problem I had with Windows complaining
about some of my file names being too long when combined with my file path.

**Comment by JaspalSuri** [comment]
Hi @lnolan5017, thank you for letting us know! That's great to hear. 🙂

**Comment by baptiste-grob** [comment]
Glad to hear that fixed your issue @lnolan5017!
