### ISSUE TITLE
Bottom part of letters cut off in note titles

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/web#543]
In the pane showing the list of notes, the very bottom part of the letters in the note title are cut off.

I am running under Windows 10. This happens in the latest versions of Chrome, Edge and Firefox running the browser version and also in the Windows App version 3.6.7.

The note title in the editor pane is fine. Letters are not truncated.

The easiest way to see the truncation is to use lowercase g and j in the title which end up looking like q and i.

I have attached a screen shot. You will notice I made a long title that is displayed over 3 lines. In this case, it is only the last line that truncates the bottom of the letters. 
![image](https://user-images.githubusercontent.com/81375814/115037826-e0e31f80-9e9c-11eb-8374-85aa4958f76d.png)

**Comment by JaspalSuri** [comment]
Hi @lnolan5017, thanks for taking the time to create a report for this issue. A fix for this issue will be included in future short-term releases of the web & desktop apps. 🙂

**Comment by antsgar** [comment]
Hi @lnolan5017! This issue should be fixed since version 3.6.8 ☺️

**Comment by lnolan5017** [comment]
Yes. It is displaying properly now.

Thanks.
