### ISSUE TITLE
Import Extension does not work

### ISSUE THREAD

**Issue by oliveconstant** [standardnotes/web#544]
When clicking on `Import Extension`, after pasting the link to the extension in the input field and pressing the `Enter` key, nothing happens.

Standard Notes version: 3.6.7
Browser: Firefox 86.0.1
OS: Linux

**Comment by oliveconstant** [comment]
Closing because the issue was caused by a broken extension link.

**Comment by JaspalSuri** [comment]
Sorry to hear that, @oliveconstant. Thank you for letting us know!

**Comment by oliveconstant** [comment]
As a suggestion, it would be nice if Standard Notes showed an error message instead of silently failing.

**Comment by JaspalSuri** [comment]
Thanks for the feedback! Do you still happen to have the broken link available so that way I can see when it fails?

**Comment by oliveconstant** [comment]
> Thanks for the feedback! Do you still happen to have the broken link available so that way I can see when it fails?

Here it is: https://jakecza.com/cloud/projects/sn-extensions/dark-hybrid-theme/dark-hybrid.json
