### ISSUE TITLE
Cannot write to local database when using Standard Notes in a Private Browsing Session on Firefox

### ISSUE THREAD

**Issue by bxff** [standardnotes/web#557]
**Describe the issue**
I am trying to use Standard Notes on a sandboxed environment for security reasons. My main goal is to make Standard Notes work on Tor, but unfortunately I am unable to the error is given in the 'To Reproduce' section. I know this is a known issue but is there a work around that I can use.

**To Reproduce**
1. Run Tor / Firefox on private mode
2. Go to the app: `https://app.standardnotes.org/`
3. See error:
  * `Unable to write to local database. Please restart the app and try again.` then click OK.
  * `There was an issue loading your offline database. This could happen for two reasons: 1. You're in a private window in your browser. We can't save your data without access to the local database. Please use a non-private window. 2. You have two windows of the app open at the same time. Please close any other app instances and reload the page.`

**Expected behavior**
The app should run without any error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Tor / Firefox private window
 - Version: Latest

**Additional context**
I know this is a known issue but I never encounter something like this neither on Firefox private window nor Tor.

**Comment by JaspalSuri** [comment]
Hi @bxff,

Thank you so much for bringing this issue to our attention! I was able to reproduce the issue and have forwarded it to our dev team for further review. 🙂

**Comment by bxff** [comment]
Is there any estimate on when will this issue be fixed?

**Comment by mobitar** [comment]
IndexedDB is not available in a Firefox private window, so this issue is unfixable I'm afraid.

**Comment by jackyzy823** [comment]
Under Firefox `about:config` , you can set `dom.indexedDB.privateBrowsing.enabled` to `true` to make indexeddb work under  private mode. See https://bugzilla.mozilla.org/show_bug.cgi?id=1639542#c9
