### ISSUE TITLE
Problem with web v3.6.8 with loading notes, quick tags and folder components

### ISSUE THREAD

**Issue by rusty1281** [standardnotes/web#558]
Hello,

since updating to the latest version (just noticed it today) the web notes app is not loading correctly.

There is a problem with loading folder components in the left bar, as well as main note tools, and any extension that needs to be loaded for that specific note.

<img width="406" alt="Screenshot 2021-05-17 at 13 52 31" src="https://user-images.githubusercontent.com/5110408/118484099-218dbd00-b717-11eb-916f-9fcd48592c15.png">

<img width="196" alt="Screenshot 2021-05-17 at 13 52 50" src="https://user-images.githubusercontent.com/5110408/118484141-2ce0e880-b717-11eb-8716-e64d8b644cce.png">

Extension URL works fine, login into the server works fine as well (all self-hosted).

This happens **only** for the web client on **multiple browsers**, and works with 0 problems on the mobile (iOS) or desktop (macOS). One thing to add here is that the same thing happens when running it without reverse proxy.

The complete setup is running in Docker, and again, the only problem is with the web client. That container was completely recreated but the problem is still present. For the past 8-9 months there was no issues.

Also, to note, recently there was a change with the extension URL, but after the change, web access was running without any problems. Just noticed this problem today when I invoked web access. 

The problem is while using STABLE and LATEST tag

This was also tested from a remote location on a completely different system and the result is the same.

Thank you in advance.

**Comment by rusty1281** [comment]
UPDATE: looks like the problem is the new extension's setup. As soon as I disable all the extensions, I am able to run the web UI as normal.

**Comment by rusty1281** [comment]
FINAL UPDATE: it was the extension problem. I have not unregistered the old URL as it should be, so the extensions were still pointing to the old URL in the old JSON file. Once I have fixed that, it all started to work just fine.

Also, the Advanced markdown editor didn't have the correct URL because the folder structure for the 1.3.11 version is wrong. Again correction in the JSON file and adding a new URL, fixed loading up of that specific extension. 

This matter is closed.

**Comment by JaspalSuri** [comment]
Hi @rusty1281, I apologize for the delayed response. Thank you for letting us know that the issue has been resolved. I'll forward your findings over to our Extensions dev for review.
