### ISSUE TITLE
Web UI fails to start unless new variable SF_NEXT_VERSION_SERVER is populated

### ISSUE THREAD

**Issue by eric-pierce** [standardnotes/web#577]
In the most recent update to the docker image, the WebUI refuses to start unless `SF_NEXT_VERSION_SERVER` is populated as an environment variable. Populating with the same value as `SF_DEFAULT_SERVER` appears to work.

If this variable is not populated errors are thrown in the console and the only content rendered in is a white screen.

**Comment by JaspalSuri** [comment]
Hi @eric-pierce, thanks for bringing this issue to our attention. I'll forward it over to the dev team for review. 🙂
