### ISSUE TITLE
Automatic Parent Folder Tag Adding

### ISSUE THREAD

**Issue by Sadileon** [standardnotes/web#580]
**Describe the bug**
Not sure if it falls under the "bug" label, but it definetly is bugging me since the new update. Using the Folders extension, when you want to tag a note, all parent folder tags apply automatically and cannot be removed in order to leave just the desired subfolder one. This complicates my personal note managing system, where you from the new update now cannot view just the notes tagged as the parent folder and all the notes from the subfolders show up as well. To give an example, imagine a situtation where you have folders ParentFolder and ParentFolder.ChildFolder, and want to view just the notes tagged as ParentFolder. You can no longer do that by clicking on the ParentFolder name anymore, since it will show all the ChildFolder notes aswell, since you cannot remove the parent folder tags. Hope this will get fixed or addressed as soon as possible, since it now renders my note view system on PC completely unusable. It DOES NOT do make this problem happen on the iOS vesion so far.

**To Reproduce**
1. Install "Folders" extension.
2. Create folder "ParentFolder".
3. Create folder "ChildFolder" inside the "ParentFolder".
4. Create note "Note1" and move it / tag it as "#ParentFolder".
5. Create note "Note2" and move it / tag it as "#ParentFolder.ChildFolder".
4. Click on folder "ParentFolder".
5. It now shows both the notes tagged as "#ParentFolder" and "#ParentFolder.ChildFolder", instead of just the ones tagged by the folder you clicked on, since you cannot remove the "#ParentFolder" tag while keeping the "#ParentFolder.ChildFolder" one. There's no workaround for this as far as I know, apart from using my phone of course.

**Expected behavior**
Either the tags from the master folders should not be filled automatically when assigning a subfolder tag to a note, or you should be able to remove the parent folder tags while still keeping the subfolder ones.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser 
 - Version 3.8.2

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.7
 - Browser
 - Version 3.6.10

**Additional context**

**Comment by antsgar** [comment]
Hi @Sadileon! Thank you so much for pointing this out. Our intention was for be added/deleted following the tag tree structure, but we realize this has disallowed users to customize this behavior. We'll be rollbacking the recursive tag deletion for our next update 🙂

**Comment by Sadileon** [comment]
Thank you! Is there an estimated release date for the next update yet? 🙂

**Comment by antsgar** [comment]
We'll likely have 3.8.3 ready to ship either today or tomorrow 🚀

**Comment by Sadileon** [comment]
Awesome. Thanks a lot for the services you guys provide!
