### ISSUE TITLE
Vertical resize bar obscures scrollbar

### ISSUE THREAD

**Issue by danyusf** [standardnotes/web#582]
**Describe the bug**
Vertical scroll bars for the list of notes, or the text buffer, overlap slightly with a UI indicator for resizing the frame. This happens on both Mac and Windows, so I assume it's maybe an issue with Electron. 

**To Reproduce**
with the vertical scroll bar showing for a long list of notes, move the mouse cursor to the right of the scrollbar so that it changes into the 'resize' cursor. A large gray vertical bar shows up that runs the vertical length of the frame and partly obscures the scrollbar, which is annoying if you were trying to move the mouse to the scroll bar to manipulate the scroll bar.

**Expected behavior**
In most apps with resizeable frames, no extra bar appears when the cursor changes to resize mode.

**Screenshots**
See attached screenshot for an example of the issue.

<img width="221" alt="Screen Shot 2020-07-18 at 12 16 23 PM" src="https://user-images.githubusercontent.com/25396753/87860549-49dc3d80-c8f3-11ea-9444-994574d3a253.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Issue is seen in the local Standard Notes client, but if you need this info, I'm using Chrome v84.x

**Smartphone (please complete the following information):**
N/A -- I only have this issue on desktop devices

**Additional context**
Thanks for making Standard Notes!

**Comment by JaspalSuri** [comment]
Hi @danyusf, this was fixed in `v3.8.6` of the web and desktop apps. Feel free to let us know if you have any additional questions and/or feedback!
