### ISSUE TITLE
Styling bug in the search options

### ISSUE THREAD

**Issue by dec0dOS** [standardnotes/web#583]
Hello, Standard Notes team!

Please check out the recording:

https://user-images.githubusercontent.com/14824142/122367480-238cab00-cf65-11eb-8613-56ae5c5dc77d.mov

It is reproducible on macOS and the web.
SN desktop version: 3.8.3

**Comment by JaspalSuri** [comment]
Hi @dec0dOS, thank you for bringing this issue to our attention! I've been able to successfully reproduce the issue and will create a report for the dev team to review. 🙂

**Comment by antsgar** [comment]
Fixed on version 3.8.10 🙂
