### ISSUE TITLE
Toolbars are misaligned by a few pixels

### ISSUE THREAD

**Issue by pwseo** [standardnotes/web#584]
StandardNotes' toolbars for the "All Notes" and note content panels are misaligned by a few pixels, like so:
![image](https://user-images.githubusercontent.com/95953/122625598-03143c00-d09e-11eb-85c3-247da8f4acd2.png)
It should be a relatively easy fix (could even probably be fixed by a theme), but should still be fixed app-wide and not with a theme.

**Comment by JaspalSuri** [comment]
Hi @pwseo, we're aware of this issue and it's on our list of things to fix. 🙂 It will be addressed as a result of the redesign planned for v4.0 if it isn't fixed sooner.

**Comment by pwseo** [comment]
@JaspalSuri thank you for the clarification. Is there a publicly accessible version of the list of issues you're working on? I don't want to bother the team with issues you're already aware of :)

**Comment by JaspalSuri** [comment]
Hi @pwseo, most of the (reproducible) issues actually should be on GitHub, as we receive reports from other public mediums such as reddit and Slack. I have been keeping track of them internally so far; I apologize for not creating threads for reproducible issues on GitHub.
