### ISSUE TITLE
Search Filter popup disappears behind Views/Tags pane

### ISSUE THREAD

**Issue by lnolan5017** [standardnotes/web#585]
If I resize the All Notes pane to be smaller than the search filter popup, it disappears behind the Views/Tags pane.

Version 3.8.5 of Standard Notes running on Windows 10

![image](https://user-images.githubusercontent.com/81375814/122647828-1d790480-d0f4-11eb-800a-ea092f8e95ca.png)

**Comment by JaspalSuri** [comment]
Hi @lnolan5017, thanks for the report! We're aware of this issue and it's on our list of bugs to fix. 🙂

I am going to close this thread since it's a duplicate of #583.
