### ISSUE TITLE
Keyboard navigation broken with new tags

### ISSUE THREAD

**Issue by tim-kilian** [standardnotes/web#589]
It's now hard to navigate from the title to the tag input and finally to the text editor.

**Comment by tim-kilian** [comment]
Now, after the #591 fix it is even worse to navigate through.
I can not tab into the tags input and need to use my mouse to add tags.

**Comment by JaspalSuri** [comment]
>I can not tab into the tags input and need to use my mouse to add tags.

Hi @tim-kilian, for what it's worth, you can use the arrow keys to navigate towards the tags text field.

**Comment by JaspalSuri** [comment]
Whenever someone opens a note they can tab multiple times reach the body's text field without having to cycle through multiple tags, especially as users might not modify the tags section as frequently as the title or body or a note.
