### ISSUE TITLE
Add button or key combination to clear search filter

### ISSUE THREAD

**Issue by matze** [standardnotes/web#59]
Searching is fast and easy whereas clearing requires either marking the entire search field and then hit backspace or delete all the characters manually. A simple `x` button next to the search field or a key combination that clears it would improve interaction tremendously.

**Comment by mobitar** [comment]
SN is all about the complexity vs convenience tradeoff. This adds complexity with a very small return on convenience. Might not be worth it.

**Comment by matze** [comment]
When all I do is searching again and again, return on convenience piles up quickly …

**Comment by mobitar** [comment]
What about cmd/ctrl + a, then backspace? Wouldn't that be the same?

**Comment by matze** [comment]
Hmm, yes I guess it'll do.
