### ISSUE TITLE
Not all notes are indexed

### ISSUE THREAD

**Issue by matze** [standardnotes/web#61]
When searching for notes that are not yet in the browser view, I cannot find them. Scrolling through the list and loading the remaining notes allows them to be found again. Ideally, all notes should be indexed from the time I open the page.

**Comment by mobitar** [comment]
Ahhh you're right. Can't believe I missed this. Well that sucks. There goes my infinite scroll fix for higher performance for large number of notes. Will have to think of a better solution.

**Comment by mobitar** [comment]
Ok I may have overreacted. The solution turned out to be quite simple. Pushing to web app now. Desktop apps will receive update later this week probably.
