### ISSUE TITLE
'Sync Unreachable' error

### ISSUE THREAD

**Issue by Larch35** [standardnotes/web#611]
I'm using the web app (3.8.18) in Firefox 90 on W10 and have noticed recently that sync attempts keep failing. If I click into the Account menu, the red error box says "Hmm... we can't seem to sync your account. The reason: Unknown error". I found a similar issue on here from a couple of years ago and I saw that logging out and back in was recommended. However, when I went to sign out, I was warned that I have 11 notes that have not been synced so my changes would be lost. Obviously I don't want that to happen, and unfortunately I can't remember which notes I've updated since the problem arose (I think I just didn't notice the error at first).

I'm wondering how I can resolve this without losing my changes or ending up with two versions of my notes and wondering where the differences are and which version is the latest. Can anyone advise, please?

**Comment by JaspalSuri** [comment]
Hi @Larch35, please export a backup of your notes via the **Account** menu, verify that the contents are non-empty, then sign into the [web app](https://app.standardnotes.org), sort your notes on the Desktop and Web apps by **Date Modified**, compare the titles, bodies, and tags lists of each of the most recently updated notes by making the changes on the Web app, then sign out of the desktop app and sign back in.

**Comment by Larch35** [comment]
Hi @JaspalSuri - thank you, I will give that a try.

**Comment by Larch35** [comment]
Right, that was a bit laborious in terms of comparing the contents as some of my notes are pretty big, and updates can be anywhere in the body, but I think I'm back in sync now - fingers crossed it stays that way.

Thanks again for your help.
