### ISSUE TITLE
Bug when unlocking app

### ISSUE THREAD

**Issue by hillbilly3456avk** [standardnotes/web#627]
**Describe the bug**
When I enter a wrong Passcode very fast after typing the correct Passcode, the Desktop app unlocks, but the "Authentication Required" remains in the foreground, making it impossible to interact with the App. App must be closed eventually

**To Reproduce**
1. Desktop App: configure a Passcode
2. Open the app, wait for the Authentication Required" Pop-up
3. Enter the correct Passcode
4. Hit Enter an then immediately an additional key and again Enter

**Expected behavior**
the second attempt to unlock should be ignored since the app has received the correct Passcode

**Desktop (please complete the following information):**
 - OS: Linux/Windows10
 - Browser n/a
 - Version 3.8.18 / 3.8.21

**Comment by antsgar** [comment]
Fixed in commit https://github.com/standardnotes/web/commit/c55946cb54d87459b6d91c47fd93f987e5bc4a53
