### ISSUE TITLE
[Feature Request] Hierarchy Support

### ISSUE THREAD

**Issue by HackToHell** [standardnotes/web#66]
Hey, really love your application, been using it a lot. One thing I would love to have extra is an hierarchy based notes structure like OneNote ! 

Tags are awesome but very soon the notes become cluttered and it's harder to track things now.

**Comment by mobitar** [comment]
Hey, thanks. Can you show me an example of how they are becoming cluttered?

**Comment by HackToHell** [comment]
hey, I am basically using it for taking notes on *everything*. Problem is that sometimes, notes get multiple overlapping tags. Say there's work related notes, say I have the tags #work to differentiate that from normal notes, problem is that sometimes, I accidentally end up setting other notes from a domain(I have a fitness domain) and there I used the #work tag for planning up a diet. The problem is amplified with multiple tags and multiple domains. With say even a single tree, I can split it and it will be awesome :).

**Comment by mobitar** [comment]
By domains do you mean like topics? Or like www.domain.com?

**Comment by HackToHell** [comment]
yeah I meant topics, like work domain has notes related to work etc.

**Comment by mobitar** [comment]
This problem will likely be tackled in the form of extensions, but we're still pretty far from it.
