### ISSUE TITLE
Crypto: UUID is not generated securely

### ISSUE THREAD

**Issue by terrorbyte** [standardnotes/web#7]
Issue
--------
The web interfaces does not generate random UUIDs using a cryptographically secure random number generator. This could lead to potentially deterministic generation of UUIDs

See:
* https://littlemaninmyhead.wordpress.com/2015/11/22/cautionary-note-uuids-should-generally-not-be-used-for-authentication-tokens/
* http://hg.openjdk.java.net/sandbox/jdk7/jdk/file/3a3c4785e7a7/src/share/classes/java/util/UUID.java#l171

Resolution
--------------
Use a cryptographically secure RNG for generating UUIDs

Location
------------
* https://github.com/standardnotes/web/blob/e79bc29b89489d813e6ea614ce227f0e24881e95/app/assets/javascripts/app/services/helpers/crypto.js#L13

**Comment by mobitar** [comment]
Javascript is very wanting of an RNG. I've added support for WebCrypto, but haven't yet migrated UUIDs. I'll have to take a look to see if WebCrypto supports generating UUIDs.

**Comment by mobitar** [comment]
Closed via 18eae51067d29385f254963b94f2348b3d137eee
