### ISSUE TITLE
Extensions list does not automatically update

### ISSUE THREAD

**Issue by Parkertg** [standardnotes/web#744]
version 3.9.3 Desktop App windows 10

When Adding a new external extension OR deleting an external extension,
the extensions list does not update until you exit the menu and reopen it.

![image](https://user-images.githubusercontent.com/46120246/141525461-aafbf408-eec0-4cee-baa5-5934ebb2dc7d.png)

**Comment by vardan-arm** [comment]
Hi @Parkertg, I tried locally with some external extensions, but couldn't reproduce the issue (app version 3.9.3, Windows 10). Could you please give the link of the extension so I can try with it as well?
BTW, there is also [3.9.4](https://github.com/standardnotes/desktop/releases/tag/v3.9.4) version of desktop app, you could also try it and see whether it happens there.

**Comment by Parkertg** [comment]
Yea, seems to work now on 3.9.4
