### ISSUE TITLE
Long loading time-duration when using custom editors

### ISSUE THREAD

**Issue by Saldef** [standardnotes/web#757]
When I open a note that is edited in a custom editor it takes too much time to open, between 1-2.5 mins (I actually measured it with a stopwatch, multiple times, with multiple notes, and multiple custom editors), but it instantaneously opens if I switch to a native editor. Not sure if this related to the [recent shift from SN team](https://github.com/standardnotes/web/issues/713) to remove the Extension Manager in favor of native extension handling, which might explain the loading speed disparity. 

This LONG loading time appeared for both the [Append Editor](https://github.com/theodorechu/append-editor) and the [Fast Editor](https://github.com/dec0dOS/standard-notes-fast-editor), interestingly, it was not the case with the [Rich Markdown Editor](https://github.com/arturolinares/sn-rme) but still longer by up to 10 seconds than the native editors. In the case of the Fast Editor, after approximately a minute and a half a webpage appears saying `The connection has timed out. An error occurred during a connection to raw.githack.com.........` [see image](https://ibb.co/DMvQTKP). 

Waiting for more than a minute to take note, or open it, is not an option. So please how to solve this issue?

**Comment by moughxyz** [comment]
Nothing on our end. I'd open the Network tab in your dev tools and see what's going on with the request.
