### ISSUE TITLE
Password exposed unintentionally during sign-in

### ISSUE THREAD

**Issue by gapop** [standardnotes/web#766]
**Describe the bug**
During sign-in, the password can be exposed without the user activating the _Show password_ button.

**To Reproduce**
1. Go to https://app.standardnotes.org/
2. Press down arrow key to select _Sign In_ from the bottom-left menu.
3. Using the Tab key to navigate the Sign In form, enter email and password, then keep pressing Tab to reach the _Stay signed-in_ checkbox.
4. Press Space to uncheck the checkbox.
5. Press Enter to submit the form.

**Expected behavior**
When pressing Enter, the keyboard focus is on the checkbox. The form should either be submitted or nothing should happen. Instead, the password is being exposed, as if the focus had remained on the _Show password_ button.

**Desktop (please complete the following information):**
 - OS: Kubuntu 21.10
 - Browser: tested in Firefox 94 and Brave 1.32.115

**Comment by moughxyz** [comment]
This was fixed shortly after being reported.
