### ISSUE TITLE
No notes shown in "All Notes" pane

### ISSUE THREAD

**Issue by CountCypher** [standardnotes/web#798]
Hi,

I'm self hosting Standard Notes Web on a Raspberry Pi 4 and deployed it following the instructions stated under "[Running locally](https://github.com/standardnotes/web#running-locally)". I'm using Nginx as reverse proxy on another SBC. 

I can access SN Web and log in. I can also create new notes with the "+" button. The syncing also seems to work, because the newly generated note gets saved and updated and it also shows up immediately in a different client (SN Desktop App).

The problem is, that no notes are shown in the "All Notes" pane, i.e. I cannot access any of the existing notes in SN Web. I'm testing this in Chromium, btw. Browser console gives me this error (not sure if it is related to the problem):

`WebSocket connection to 'wss://snotes.mydomain.com:3001/ws' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

Is there maybe somethin wrong with my Nginx config? Pasting it here for reference:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    index index.php index.html index.htm;

    server_name snotes.mydomain.com;

    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

    location / {
        proxy_pass http://192.168.178.62:3001;
    }

}
```
Thanks in advance for your help. :)

**Comment by moughxyz** [comment]
Hmm, best we can do is have you share your domain so I can test it out. Feel free to email me. Otherwise make sure the web app image is based on the main branch and not develop.

**Comment by CountCypher** [comment]
@moughxyz Thanks for the great support! 

Indeed it seems the issue was that I've used the develop branch, not the main branch (I had used `git clone https://github.com/standardnotes/web.git`). Maybe it's helpful to others - this is how I deployed it in the end:

```
git clone -b main --single-branch https://github.com/standardnotes/web.git
cd web
cp .env.sample .env
yarn setup
yarn build
rails s -b 0.0.0.0 -p 3001
```
