### ISSUE TITLE
Ctrl-M does not show rendered Markdown anymore

### ISSUE THREAD

**Issue by matze** [standardnotes/web#80]
For some time, <kbd>Ctrl</kbd><kbd>M</kbd> used to switch between editor window and rendered Markdown content, however right now all I see is the tab being muted and unmuted. Is there a key combination or option to see the rendered Markdown?

**Comment by mobitar** [comment]
Hey, Markdown was removed from the core app and bundled into an extension. You should install the Simple Markdown Editor extension instead: https://standardnotes.org/extensions/simple-markdown

**Comment by matze** [comment]
Hmm, I am note really convinced because UX is much worse now. Switching is a click-fest and on my half-wide browser tab, the four columns are pretty narrow. I see two things that could make this more useful: 1) enabling the Simple Markdown editor should affect all notes and 2) the preview may be shown below the note editor not to the right.

**Comment by mobitar** [comment]
For 1, you have to enable it per note since the editor is allowed to access that note unencrypted (it has to to be able to display it with formatting).

2, good feedback. Will see if I can make that an option.

This is just the first release of editor extensions. In the future, you might be able to set keyboard shortcuts to quick toggle to different editors.

**Comment by keybits** [comment]
I really miss the shortcut to toggle markdown preview and edit mode. Having two panes (either horizontally or vertically) is distracting.

It would be great if you can reinstate the toggle option keyboard shortcut without additional panes. Thanks :-)

**Comment by mobitar** [comment]
You can just collapse the panes to the edges:

<img width="836" alt="screen shot 2017-03-18 at 11 36 19 am" src="https://cloud.githubusercontent.com/assets/3277844/24074011/1ff742f6-0bcf-11e7-85da-c6f60fe07578.png">

Isn't that the same thing?

**Comment by keybits** [comment]
Thanks for the suggestion. Doesn't feel as elegant as the old behaviour.

While I'm here - thank you so much for your work on Standard Notes - I'm super impressed and will try to help out when I get some time.

**Comment by mobitar** [comment]
Thank you, appreciate it :)
