### ISSUE TITLE
Folders extension stops working when Standard Notes web is reloaded or restarted

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/web#818]
The Folders extension stops working when I reload Standard Notes or restart the broswer. A message says: "There was an issue loading Folders", and it won't go away the I press the "Reload" button. The error occurs on both Linux and Windows.

A temporary solution is to deactivate and then activate the Folders extension in Quick Settings. Another solution, also temporary, is to sign out and sign in again.

**Comment by stefan-yas** [comment]
Thanks for the report @onlinemumie! We're aware of the issue and are working on a solution.

**Comment by onlinemumie** [comment]
It seems to be solved now, so I will close this.

**Comment by onlinemumie** [comment]
I must reopen this. The problem is back and even worse than before. Now it affects Standard Notes desktop version as well. What on earth is happening?

**Comment by stefan-yas** [comment]
We're currently in testing phase and will be releasing native Folders soon which should deprecate the extension and resolve all issues related to Folders.

**Comment by onlinemumie** [comment]
Any temporary solution while we're waiting? At the moment, I must turn folders off-on or sign out and clear data constantly to get folders to work.
