### ISSUE TITLE
Changed tags don't propagate across devices

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/web#82]
When removing a tag on mobile or web, the change does not propagate automatically until the next manually triggered sync. Tag changes should be pushed across devices in the same way note edits are pushed.

**Comment by CR0CKER** [comment]
Actually, it seems that newly added tags do propagate after manual sync, but if I remove a tag on an iOS device, that tag never disappears on the desktop version. Newly added tags do appear though.

**Comment by mobitar** [comment]
This issue should be fixed with the latest release.
