### ISSUE TITLE
Change standard font on desktop app or allow to set standard font on each device.

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/web#83]
This doesn't need to be rich text, but just which font to use to display all notes on a device. The current font used in the desktop app is horrible and not consistent with macOS system settings.

**Comment by mobitar** [comment]
Yeah not really sure what the issue with the desktop app font is. I've tried everything to fix it but can't seem to find a solution.

**Comment by mobitar** [comment]
Actually, just found a solution. Will push out soon. It will be a slightly different font for desktop vs web, but I think it's still preferable to the current desktop font.
