### ISSUE TITLE
[3.10.0] Themes are unloaded after passcode screen

### ISSUE THREAD

**Issue by BarbossHack** [standardnotes/web#866]
Hi,

Since today v3.10.0 release, themes are unloaded after login.

Steps to reproduce : 

1. Install `Gruvbox Dark Theme` with this link `https://listed.to/p/4WoQA6pLdV` (https://github.com/christianhans/sn-gruvbox-dark-theme).
2. Activate the theme, theme is loaded, everything is ok.
3. Refresh the webpages (or close/reopen your `v3.10.0` desktop app), you are now on the passcode page, with the `Gruvbox` theme, everything seems ok.
4. Enter your passcode.
5. You can now see your notes, but the theme switch to default one 1 second after (`Gruvbox` is still selected in themes selection).

Precisions:
- The bug happens on web and desktop, 3.10.0
- `Gruvbox` theme was working fine before today, so I assume it's a problem in v3.10.0
- There is not stack trace or debug logs in the javascript console (chrome)...
- In "preferences >> Appearance >> Themes", "Use system color scheme" is disabled for my account (web and desktop).

Thank you !

**Comment by moughxyz** [comment]
Thanks, fix is confirmed and will be included in 3.10.1.

**Comment by moughxyz** [comment]
Fixed in 3.11: https://github.com/standardnotes/desktop/releases/tag/v3.11.0

**Comment by BarbossHack** [comment]
Thank you @moughxyz ! Bug is fixed
But there is an other (little) problem, if you remember my "steps to reproduce"
> 3. Refresh the webpages (or close/reopen your v3.10.0 desktop app), you are now on the passcode page, with the Gruvbox theme, everything seems ok.

Now, after refreshing (ont he passcode page), but instead of `Gruvbox` theme I only see the default white theme. Then I write my passcode, it's loading, and then it switchs to `Gruvbox theme` and everything is fine. 
But the fact that we can see the "switch" between the two themes is a bit disturbing...

Thank you !

**Comment by BarbossHack** [comment]
Seems to be fixed in 3.11.1 
Thank you ! 👍
