### ISSUE TITLE
Sub-tags support

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/web#88]
Just wondering if there has been any thoughts on implementing sub-tags in standardnotes

example would be 

you have a parent tag of `projects` then a sub-tag for each of your many projects - this way the sub-tags don't clutter the tag list 
* assume you can expand/collapse tag parents to show/hide the sub-tag so the tag list is manageable even with lots of tags

a note in a project tag could also be tagged to a person or a place/event - if you have a people and event parent tags - you can hide/manage all the sub-tags

so could be tagged as `#projects/web #people/joe #calendar/2017-03`

this way you could view all notes assigned to `joe` or view all notes for the `web` project or all projects due in March etc..

heres a screenshot of how some people use sub-tags in evernote;
* https://michaelhyatt.com/wp-content/uploads/2014/05/evernote-screenshot-03.png

**Comment by mobitar** [comment]
This would be better left to extensions, when the time comes to expand extensions to support these kinds of things. Stay tuned.

**Comment by justinkelly** [comment]
thanks - i look forward to seeing what else is possible with extensions
