### ISSUE TITLE
View file attachments online

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/web#89]
Great work on the file attachment extension!!!

One suggestion:

Please can you allow the user to view/preview the file online rather than download the file

What happens
* attach image to a note
* when you go to open the attachment it downloads

Whats expected
* attach image to a note
* when you go to open the attachment it opens in a new tab (or similar such as modal overlay) 
  * so you dont have to go through the extra steps of downloading it, opening it in another program etc..
  * where possible i just want to be able to either full the full file online (where its an image,pdf,etc..) or view a preview if its a xls/doc/etc..
  * this is how trello and others work

Hope this makes sense

Thanks again for all your hard work - greatly appreciated!!!!!!!!!!!!!

**Comment by mobitar** [comment]
Hmm I can look into this. Not sure it would be trivial though. As long as it doesn't require external libraries and can just rely on the browser's rendering capabilities, then this sounds reasonable.

**Comment by justinkelly** [comment]
thanks @mobitar !

**Comment by ClarkeCC** [comment]
+1

**Comment by mobitar** [comment]
FileSafe is now the way to handle attachments through SN.
