### ISSUE TITLE
Reference attached files in note

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/web#91]
One feature that I would love to see borrowed from confluence and other wikis is to use images(or files) attached to a note to be embed/linked from the note

Example image:

```
![inline image](attachment/my_image.png)
```

In Simple Markdown view I would expect that with the above markdown it would render the attached image in the view pane on the right

Example PDF

```
[My PDF](attachment/my_file.pdf)
```
In Simple Markdown view I expect that this would render as a clickable link - when click would open the file in browser (or auto download)

Thanks again!!!!!

**Comment by mobitar** [comment]
Are you referring to your Dropbox attachments? Extensions can't communicate with one another, so unless you manually grab the link to your attachments and paste them, this wouldn't be possible.

**Comment by justinkelly** [comment]
ok - thanks for the confirmation - i'll close this one
