### ISSUE TITLE
DEFAULT_FILES_HOST is now a required variable - not in .env.sample

### ISSUE THREAD

**Issue by eric-pierce** [standardnotes/web#914]
It looks like DEFAULT_FILES_HOST is now a required variable as of c3d849d20415fa48f5f24c67508b274d29642402, but it isn't listed in the .env.sample file. When it isn't populated the web page fails to render and errors are thrown in console.

I resolved this by adding DEFAULT_FILES_HOST in my env file with the same destination as APP_HOST (ie DEFAULT_FILES_HOST=https://notes.$DOMAINNAME)

I've opened https://github.com/standardnotes/web/pull/915 to resolve

**Comment by moughxyz** [comment]
This was removed here actually just today: https://github.com/standardnotes/web/commit/6d64889aad4172c1fdc9508a93787eb2785b688a

So no longer required 👍
