### ISSUE TITLE
Tag bug that blocks the whole app 

### ISSUE THREAD

**Issue by Saldef** [standardnotes/web#933]
Here is a weird, interesting and easily reproducible bug that I discovered accidently: 

In the tag bar (or whatever it is called), type one or two letters maximum (you can't reproduce it with three or more letters) THEN type the character `[` , the whole app will just stop working, no matter what you click or do afterwards, the tag drop-down list will not disappear.  You have to exit the app and re-open it again in order for the app to function. 

I reproduced it on the desktop app on two Windows machines (while I was signed in), and on the web app as well (while I wasn't signed-in). 

***Exceptions*** : The one or two letters has to exist in previous written tags in order for the bug to be reproduced (a drop down list has to be shown) , if you have no tag or if, for example, the two letters are `qk` and there is no other existing tag that has these two letters, it won't work. 

**OS:** Windows 10 Enterprise
**Standard Notes Version :** 3.13.0

**Comment by moughxyz** [comment]
Can replicate, thanks 👍

**Comment by moughxyz** [comment]
This is fixed in the upcoming 3.14.0 release.
