### ISSUE TITLE
use https://app.standardnotes.com/ to write notes, but github-push cannot be loaded normally

### ISSUE THREAD

**Issue by dislazy** [standardnotes/web#939]
use https://app.standardnotes.com/ to write notes, but github-push cannot be loaded normally can you help me  thanks

some error:

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://app.standardnotes.com/assets/26546f131d8b2b5cc0f7.ttf?v=2.0.1
xxxxxx/v2/subscriptions:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app-ef521a757345e00667c7b9034a3577229e86ae7bf038bfca0046b6e9e221789d.js:2 Error: getaddrinfo ENOTFOUND payments
    at s.getAvailableSubscriptions (app-ef521a757345e00667c7b9034a3577229e86ae7bf038bfca0046b6e9e221789d.js:2:778607)
    at async t.SubscriptionState.getAvailableSubscriptions (app-ef521a757345e00667c7b9034a3577229e86ae7bf038bfca0046b6e9e221789d.js:2:1386489)
    at async t.SubscriptionState.getSubscriptionInfo (app-ef521a757345e00667c7b9034a3577229e86ae7bf038bfca0046b6e9e221789d.js:2:1386800)
getAvailableSubscriptions @ app-ef521a757345e00667c7b9034a3577229e86ae7bf038bfca0046b6e9e221789d.js:2
easymd.js:2 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://app.standardnotes.com/components/org.standardnotes.advanced-markdown-editor/dist/fonts/fontawesome-webfont.woff2
xxxxx/v1/items/check-integrity:1          Failed to load resource: the server responded with a status of 404 (Not Found)
api.standardnotes.com/v1/offline/features:1          Failed to load resource: the server responded with a status of 401 ()
DevTools failed to load source map: Could not load content for https://app.standardnotes.com/assets/javascripts/app.js.map;: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by moughxyz** [comment]
Sounds like a self-hosted server? We have a [fix](https://github.com/standardnotes/standalone/issues/64#issuecomment-1065337998) going out this week with some fixes for self-hosted servers with regards to that erroneous "no subscription found" message.

**Comment by dislazy** [comment]
> Sounds like a self-hosted server? We have a [fix](https://github.com/standardnotes/standalone/issues/64#issuecomment-1065337998) going out this week with some fixes for self-hosted servers with regards to that erroneous "no subscription found" message.

Yes, but I installed two plugins, an Action Bar and a github-push, but the Action Bar works perfectly fine, and github-push closes as soon as it opens after adding the repository

**Comment by dislazy** [comment]
> I don't think the errors you posted originally are related to the issue with GitHub Push. What do you mean by "closes" when you add a repository? Can you capture a screen recording?

Action Bar normal
![1](https://user-images.githubusercontent.com/30426054/159619220-85ccb372-b65e-440b-826a-4bd20f98d849.jpg)

github-push loading
![2](https://user-images.githubusercontent.com/30426054/159619230-763c3b14-d3f7-416e-a937-f125fd4bf577.jpg)

click github-push but can not open
![3](https://user-images.githubusercontent.com/30426054/159619241-3d4ffb1a-5eb4-48d7-98ad-bf1d8f274bc4.jpg)
