### ISSUE TITLE
Advanced editor - please make code block better

### ISSUE THREAD

**Issue by justinkelly** [standardnotes/web#94]
When using the advanced markdown editor

What I expect
* when editing a code block - using ``` or 4 spaces
* i expect that code block in the edit view is like an embedded ACE editor or similar
** trying using dropbox paper or evernote code blocks - they look real nice in the edit view - not just the read view

What happens
* when editing the code block only the background of the typed letters is grey and has white lines between the code lines
* refer image below for example

![selection_028](https://cloud.githubusercontent.com/assets/249520/23778930/62bb07ec-0591-11e7-9653-6a794d873a68.png)

**Comment by mobitar** [comment]
The advanced editor is based on https://github.com/NextStepWebs/simplemde-markdown-editor, so I would report this issue there for a real shot at a fix.

**Comment by justinkelly** [comment]
thanks mo - i'll post an issue there
