### ISSUE TITLE
App crashes after update to 3.14.0 when spell check enabled 

### ISSUE THREAD

**Issue by Lissy93** [standardnotes/web#954]
Hey SN team! Awesome work on the recent updates, am loving the UI upgrades and mobile performance improvements :)

Am facing an issue since updating to 3.14.0 on the desktop app, a few seconds after opening a note, the app crashes and my CPU is maxed out.

### Possible Cause
This seems to only happen when opening notes which contain multiple spelling errors (so most of my notes, lol). But after disabling spell check, things work perfectly again. 

### Environment
Only happens on the desktop app, on Windows - web app works fine, as does the Linux desktop app (on Manjaro).

### Steps to Recreate
Launch app (3.14.0), open a note with many spelling errors, observe crash

### Additional Info
Tried to create a mem dump, but realised it contains unencrypted data, so in the meantime here's the Performance report, which sort-of shows where it's freezing.
<p align="center"><a href="https://i.ibb.co/3yH1PRY/s-notes-mem-2.png"><img width="500" src="https://i.ibb.co/3yH1PRY/s-notes-mem-2.png" /></a><p>

Could it be the Electron webFrame's [`getWordSuggestions`](https://github.com/electron/electron/blob/main/docs/api/web-frame.md#webframegetwordsuggestionsword) although that code hasn't been updated in a while, so unlikely to cause a new bug. If this is Electron, feel free to close, and I can look into it further and raise an issue with them.

**Comment by moughxyz** [comment]
Hey @Lissy93, thanks for reporting, fixed in 3.14.1: https://github.com/standardnotes/desktop/releases/tag/v3.14.1

**Comment by Lissy93** [comment]
Awesome, that fixed it 🙌
Thanks for the fast response :)
