### ISSUE TITLE
Browser `prompt` not supported on windows desktop app

### ISSUE THREAD

**Issue by matthewpucc** [standardnotes/web#96]
The [prompt](https://github.com/standardnotes/web/blob/052c6a9cde4c3fd826edc002145166ee0f0d7c76/app/assets/javascripts/app/services/directives/views/accountMenu.js#L101) call on the desktop app is returning the error that prompt is not supported.

Steps to reproduce:

- Open the windows standard notes.
- Open developer console
- Click account while logged out
- Enter new account information
- Click Register
- Check for error

**Comment by mobitar** [comment]
Woah! Good catch. Can't believe I missed this. Will have to find another solution. Please register using the web app for now.

**Comment by matthewpucc** [comment]
Already did that once I saw what the issue was. Just wanted to give a heads up.

**Comment by mobitar** [comment]
This is fixed in the latest desktop release.
