### ISSUE TITLE
Editor fonts

### ISSUE THREAD

**Issue by netvl** [standardnotes/web#97]
Is it possible to select monospace font in the advanced editor? Similarly, it is possible to change the font in the simple editor? I really don't like that it forces the Courier font instead of my system monospace font.

**Comment by mobitar** [comment]
Can you share a screenshot of how it looks?

**Comment by netvl** [comment]
Sure. This is how it looks in the simple editor:
![screenshot_2017-03-19_20 20 05](https://cloud.githubusercontent.com/assets/280456/24082588/88e34df6-0ce1-11e7-9c8b-9a5f4be7ace2.png)
Here is advanced editor:
![screenshot_2017-03-19_20 20 56](https://cloud.githubusercontent.com/assets/280456/24082594/998e056a-0ce1-11e7-841f-8597a7a4b320.png)

As you can see, the simple editor has some Courier-like font in it, while the advanced editor has a proportional font. I would very much like to have an ability to select the font in both cases.

That being said, it is possible that Courier is used in the simple editor because for some reason I actually have "Liberation Mono" (which is an open version of Courier New) as my default monospace font:
```
% fc-match monospace             
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
```

This is strange because apparently I don't see this font anywhere else... Still, an ability to manually select the font in the simple editor would be nice. Same ability in the advanced editor is a must, in my opinion.

**Comment by mobitar** [comment]
Check out the new themes feature for Desktop. Now you can specify custom colors, fonts, layout etc. https://standardnotes.org/extensions/themes

**Comment by tommyku** [comment]
I am injecting the `dark-blue.css` into the web app using a Chrome extension. Will theme be supported on web app?

**Comment by mobitar** [comment]
I think they will be at some point. But starting out it was easier to do it in Desktop. Which Chrome extension are you using? That's pretty cool. Can you post it in forum.standardnotes.org so others can try it out as well?

**Comment by tommyku** [comment]
@mobitar the repo is at https://github.com/tommyku/standardnotes-injection. I haven't put it on to chrome extension store though.

**Comment by mobitar** [comment]
Oh wow very cool. You should post it in the forum nonetheless!

**Comment by mobitar** [comment]
Web extensions are now available.

**Comment by ebelinski** [comment]
> Now you can specify custom colors, fonts, layout etc. 

@mobitar I'm a little confused on this point. I installed a custom theme from https://standardnotes.org/extensions/ but I still don't see any way to customize the theme including font. Do you mean there is a way to create your own themes?

**Comment by mobitar** [comment]
Yes you can create your own theme. Please see: https://docs.standardnotes.org/extensions/themes.html
