### ISSUE TITLE
Web app freezes when trying to sign in on mobile

### ISSUE THREAD

**Issue by iammeline** [standardnotes/web#975]
When i try to log in with my account at app.standardnotes.com from my mobile browser nothing happens, it just keeps loading but does not connect even after waiting for a long time.

**Comment by stefan-yas** [comment]
Any reason you're not using the mobile app?

**Comment by iammeline** [comment]
When I updated the application to version 3.14.0 I couldn't enter the app because it crashed every time (as discussed in here: https://github.com/standardnotes/mobile/issues/582#issue-1192185505), then I decided to use the web version instead, but I couldn't log into my account because when I clicked on "Sign in" the site just kept loading endlessly, the problem was solved for me in version 3.14.1 but in the web app I still can't log in so I decided to report the issue here in case someone else have the same problem.

**Comment by iammeline** [comment]
So it seems that the issue is not with Standard Notes' web app but with Bromite browser (the browser I am currently using and the one I tried to log into the web app at first), I tested logging in with other mobile browsers such as Chrome, Firefox, Opera, DuckduckGo, Brave, Microsoft Edge and they all worked just fine, I don't know if there is any way to modify anything in the Standard Notes' web app code to solve the problem but I will open an issue in the Bromite repository.
