### ISSUE TITLE
Advanced editor code blocks indentation

### ISSUE THREAD

**Issue by netvl** [standardnotes/web#98]
The advanced editor indents code blocks in nested lists incorrectly. Github renders this:
~~~markdown
* hello
  ```json
  {
    "some data": 123
  }
  ```
  - world
    ```json
    {
      "more nested data": 456
    }
    ```
~~~

Like this:

* hello
  ```json
  {
    "some data": 123
  }
  ```
  - world
    ```json
    {
      "more nested data": 456
    }
    ```

But the advanced editor renders it like this:

![screenshot_2017-03-13_18 27 48](https://cloud.githubusercontent.com/assets/280456/23858729/db7ff3fa-081a-11e7-8d22-4fd7d990e53e.png)

Note that there is much more indentation than necessary, and it is inconsistent.

**Comment by netvl** [comment]
Hmm, apparently this is caused by inconsistent usage of tab characters by the editor. It does not indent with spaces, it indents with tabs. This is very noticeable if you switch the editor back to simple. It inserts them automatically e.g. when you press enter when in the code block.

Is it possible to fix? Maybe there is another good markdown editor which could be used?

**Comment by netvl** [comment]
Apparently SimpleMDE supports indentation without tabs:
new SimpleMDE({
    ...
    indentWithTabs: false,
    ...
})
```
Is it possible to allow to configure this option? Or maybe all options, by providing a JSON map?

**Comment by mobitar** [comment]
Do you think `indentWithTabs: false` should be a default option? What is the case for it?

**Comment by netvl** [comment]
I'm not sure about a case *for* it, but a case *against* it is that it makes working with properly indented code blocks harder, as you can see above. I just typed the code on the left directly in the editor, and got the results on the right. If spaces were used for indentation, the result would be much prettier.

Anyway, it would ne really great if these options were configurable.

**Comment by mobitar** [comment]
So `indentWithTabs: false` will create 4 spaces when you press the tab key?

**Comment by netvl** [comment]
I don't know - I didn't work with SimpleMDE ever, I just noticed it in the readme, and they apparently have no documentation about it. But I think so, yes; maybe 2 instead of 4 though, but I'm just guessing.

**Comment by mobitar** [comment]
I tried your code snippet and it renders like this:

<img width="697" alt="screen shot 2017-03-13 at 12 28 44 pm" src="https://cloud.githubusercontent.com/assets/3277844/23867059/b69dbf90-07e8-11e7-926e-0b0a675d71a6.png">

What's the issue with it? It looks just like Github's render.

**Comment by netvl** [comment]
Yep, I copied and pasted it and it does look good. The problem is with typing. Here I typed exactly the same text below, and it resulted in extra indentation:
![screenshot_2017-03-13_22 53 55](https://cloud.githubusercontent.com/assets/280456/23870508/1352a2f8-0840-11e7-9ba7-f822f195da06.png)
And that's how it looks in the simple editor:
![screenshot_2017-03-13_22 54 18](https://cloud.githubusercontent.com/assets/280456/23870524/1be55244-0840-11e7-918a-48be82cdeffd.png)
You can see lots of weird indentation, that's because it is full of tabs (I selected one).

**Comment by netvl** [comment]
Here I tried typing again, now using Shift+Tab and Tab where possible instead of backspacing/spacing to produce indents, the final result is still far from being pretty:
![screenshot_2017-03-13_22 59 00](https://cloud.githubusercontent.com/assets/280456/23870713/cbbce222-0840-11e7-80de-1620d7a9c9c3.png)
![screenshot_2017-03-13_22 59 27](https://cloud.githubusercontent.com/assets/280456/23870717/cf5fcbb0-0840-11e7-996b-89f3d41c67cd.png)

**Comment by mobitar** [comment]
Hmm strange. I would report this issue in the SimpleMDE repo for a good chance at it being fixed.
